aws/smithy-go

doc.go, go.mod
=> Create the initial Go module

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenVisitor.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolVisitor.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/UnionGenerator.java
This adds support for generating unions, which are interfaces with a hidden identifying method that have a set of implementing type aliases. Example:
```go
type Precipitation interface {
isPrecipitation()
}
type PrecipitationBaz interface {
Precipitation
isPrecipitationBaz()
Value() Baz
}
func AsPrecipitationBaz(v Baz) PrecipitationBaz {
return precipitationBaz{value: v}
}
type precipitationBaz struct {
value Baz
}
func (precipitationBaz) isPrecipitation()    {}
func (precipitationBaz) isPrecipitationBaz() {}
func (v precipitationBaz) Value() Baz {
return v.value
}
type PrecipitationBlob interface {
Precipitation
isPrecipitationBlob()
Value() []byte
}
func AsPrecipitationBlob(v []byte) PrecipitationBlob {
return precipitationBlob{value: v}
}
type …
```
=> Generate unions

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoStackStepMiddlewareGenerator.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolUtils.java
Some checkstyle issues managed to slip in, mostly missing periods.
=> Fix checkstyle errors

codegen/smithy-go-codegen-test/model/main.smithy, codegen/smithy-go-codegen-test/model/more-nesting.smithy, codegen/smithy-go-codegen-test/model/nested.smithy
This updates the version string to just `"1"` and updates the suppressions
=> Update test sample package to comply with 1.0

codegen/smithy-go-codegen-test/build.gradle.kts
Updates the smithy gradle plugin version to 0.5.0
=> Update smithy gradle plugin

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoWriter.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolUtils.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolVisitor.java
Fixes the namespace for member shapes that are used in maps or slices.
=> Properly namespace slice and map types

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ApplicationProtocol.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenVisitor.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoDependency.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoWriter.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/GoIntegration.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ProtocolGenerator.java
Adds support for generating "rest" bindings of non document members for operation shapes.
=> HttpBinding Serialization Support

.travis.yml, codegen/build.gradle.kts, codegen/smithy-go-codegen-test/build.gradle.kts, codegen/smithy-go-codegen-test/model/main.smithy, codegen/smithy-go-codegen/build.gradle.kts
=> Add pr tests

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoDependency.java
Updates smithy Go dependency to all use version constants.
=> fixup generated SDK dependency version

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ProtocolGenerator.java
Fixes potential collisions for operation document serializer functions.
=> Fixes potential collisions for operation document serializer functions

time/time.go, time/time_test.go
=> Smithy time formatter package

ptr/from_ptr.go, ptr/generate.go, ptr/to_ptr.go
Adds missing bool and byte types to the ptr utility package.
=> Add missing Bool and byte types to ptr package

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenUtils.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoDependency.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoWriter.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java, errors.go, httpbinding/encode.go, httpbinding/encode_test.go, httpbinding/header.go, httpbinding/header_test.go, httpbinding/path_replace.go, httpbinding/path_replace_test.go, httpbinding/query.go, httpbinding/query_test.go, httpbinding/shared_test.go, httpbinding/uri.go, httpbinding/uri_test.go, json/array.go, json/array_test.go, json/constants.go, json/encoder.go, json/encoder_test.go, json/escape.go, json/object.go, json/object_test.go, json/value.go, json/value_test.go
This PR fixes a number of bugs and issues within the current HTTP binding serialization generation.
=> HTTP Binding Serialization Improvements

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenUtils.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoDependency.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ServiceGenerator.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolVisitor.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java, errors.go, io/byte.go, io/doc.go, io/ringbuffer.go, io/ringbuffer_test.go, transport/http/client.go
Updates the import paths used by generated smithy API clients. Also minor tweaks to generated code to compile.
=> Fixup for smithy generated clients imports

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
Updates the REST-JSON payload serializer generator to use separate generation branch for payload serialization vs document http bindings.
The previous logic was generation payloads as if they were documents and `[]byte` where they would be better suited to be `io.Reader`.
=> Fixup REST-JSON payload serializer separating it from document vs payload

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ValidationGenerator.java
Fix for return validator parameters, and handling of nested validation error types.
=> Codegen fixup for validator error and return params

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ServiceGenerator.java
Changes client constructor to not return errors.
=> Change client constructor to not return error

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
Updates the smithy-go Go module dependency hash to include latest Go changes.
=> Bump generated SDK smithy-go go module dependency version

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java, httpbinding/uri.go, httpbinding/uri_test.go
Fixes serializer middleware to correctly handle Smithy URI containing query parameters
=> Fixes Serializer Middleware to correctly handle Smithy URI containing query parameters

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
Updates smithy-go module dependency version to latest committed hash.
=> update smithy-go module version to latest

transport/http/request.go
Minor documentation updates for http request.
=> transport/http: documentation update for Request

codegen/build.gradle.kts, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolUnitTestGenerator.java
Allows configuration of a protocol test client's options.
=> Configurable Test Client Options

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
Fixes HTTP header value serialization to skip nil and empty string header values.
=>  Fixup HTTP header value serialization to skip unset/nil values

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
Incrementing smithy-go Go hash to latest version.
=> Update Smithy-go Go dep to latest version

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
Updates smithy-go Go module dependency to be latest version.
=> Update smithy-go Go dependency

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
* Updates smithy-go dependency commit to use the latest change
=> updates smithy-go dependency commit

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ValidationGenerator.java
Registers the validation middleware to the operations stack if the operation requires input validation.
=> Register Validation Middleware

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ServiceGenerator.java
Changes the New client constructor take a set of optional functions for overriding client option defaults.
=> Change New Constructor Signature

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
Updates smithy-go's Go module dependency has to latest version.
=> Update smithy-go Go module

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
=> Update smithy-go hash

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
This updates the http binding generator to iterate on sorted collections whenever code is being generated so that the generated output is stable. This results in way less noise when generating code that gets committed.
This also removes a few instances of duplicated code.
=> Sort consistently in http binding generator

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/OperationGenerator.java
In order to allow RuntimePlugins to be inserted relative to the OperationSerializer and OperationDeserializer middleware, the serde middleware adder function must be generated first in the set of adds.
This change allows other RuntimePlugins to be defined that will insert middleware relative to the serde middleware.
Related to https://github.com/aws/aws-sdk-go-v2/pull/676
=> Generate operation serde middleware adder first before RuntimePlugins

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
Update smithy-go dependency version for generated code.
=> Update smithy-go dependency version

httpbinding/user_agent.go, httpbinding/user_agent_test.go, middleware/ordered_group.go, middleware/step_build.go, middleware/step_deserialize.go, middleware/step_finalize.go, middleware/step_initialize.go, middleware/step_serialize.go
* Adds a `Get` method for retrieving middleware by a given ID from a stack step.
* Adds an HTTP `User-Agent` builder.
=> Adds Get method for stack steps. Adds User-Agent Builder.

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
=> updates go hash

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java, transport/http/user_agent.go, transport/http/user_agent_test.go
Move UserAgentBuilder to transport/http
=> Move UserAgentBuilder to transport/http

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
=> Update smithy-go module hash

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
=> update go hash

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolGeneratorUtils.java
* Abstracts `isShapeWithResponseBindings` method applicable to Http based protocols into HttpProtocolGeneratorUtils.
=> Supporting change for Ec2Query and Query Deser

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
This updates rest bindings to base64 encode / decode strings with the mediatype trait when they're bound to headers.
=> Base64 encode mediatype strings in headers

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
=> Add missing ptr import

codegen/README.md
Update codegen `README.md` to include basic setup instructions
=> Update README to include setup instructions

codegen/smithy-go-codegen-test/build.gradle.kts, codegen/smithy-go-codegen/build.gradle.kts
=> Bump smithy java dependency versions

transport/http/request.go
=> Add accessor for isStreamSeekable

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
Updates's smithy-go's gohash to latest hash.
=> update smithy-go gohash

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ServiceGenerator.java
=> Write out service api version

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ServiceGenerator.java
Removes the APIOptions type alias.
=> Remove APIOptions alias type

codegen/smithy-go-codegen-test/build.gradle.kts, codegen/smithy-go-codegen/build.gradle.kts, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
This depends on :https://github.com/awslabs/smithy-go/pull/175 and thus has its commit. It also depends on https://github.com/awslabs/smithy/pull/571 which hasn't gone out in a proper release yet unfortunately.
=> Http status code binding

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenUtils.java
Fixes checkstyle issue due to missing param description
=> Fix checkstyle for CodegenUtils

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ServiceGenerator.java
=> Remove Option Getters

xml/error_utils.go, xml/error_utils_test.go
Fixes xml deser util to correctly handle empty response body in case of an error response.
=> Fix empty response body deser in case of error response

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/AddRequiredContentLengthHeader.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/RequiresLengthTraitSupport.java, codegen/smithy-go-codegen/src/main/resources/META-INF/services/software.amazon.smithy.go.codegen.integration.GoIntegration, transport/http/middleware_content_length.go, transport/http/middleware_content_length_test.go, transport/http/request.go
* Adds support for `requiredLength`trait 
=> Adds support for content-length required middleware trait

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/EnumGenerator.java
This adds a function to generated enums that lists all the possible
values.
=> Add Values method to enum types

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
Updates codegen Go module dependency for smithy-go
=> update codegen smithy-go dep version

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/EnumGenerator.java
The enum generator had been splitting and camel-casing based on
non-word characters, but that leaves underscores. This updates the
regex also split on underscores.
If the camel-casing were to produce a conflict, this will keep the
first camel-casing but leave subsequent potential conflicts
untouched.
=> Camel-case using underscore separators

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoStackStepMiddlewareGenerator.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/MiddlewareIdentifier.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/OperationGenerator.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/AddChecksumRequiredMiddleware.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/EndpointHostPrefixMiddleware.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/IdempotencyTokenMiddlewareGenerator.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/MiddlewareRegistrar.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/MiddlewareStackStep.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ProtocolUtils.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ValidationGenerator.java, codegen/smithy-go-codegen/src/test/java/software/amazon/smithy/go/codegen/GoStackStepMiddlewareGeneratorTest.java, middleware/ordered_group.go, middleware/ordered_group_test.go, middleware/shared_test.go, middleware/step_build.go, middleware/step_deserialize.go, middleware/step_finalize.go, middleware/step_initialize.go, middleware/step_serialize.go, transport/http/checksum_middleware.go, transport/http/checksum_middleware_test.go, transport/http/middleware_close_response_body.go, transport/http/middleware_content_length.go, transport/http/middleware_content_length_test.go, transport/http/middleware_headers.go
After a length discussion we have decided on holding off on implementing the full vision of stack slots. This subset PR contains some of the underlying improvements made to the stack, middleware, and codegen that we still want to carry forward.
=> Middleware and Stack Refactor/Cleanup

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ClientLogger.java, codegen/smithy-go-codegen/src/main/resources/META-INF/services/software.amazon.smithy.go.codegen.integration.GoIntegration, logging/logger.go, logging/logger_test.go, middleware/logging.go, middleware/logging_test.go, transport/http/client.go, transport/http/middleware_http_logging.go, transport/http/middleware_http_logging_test.go
Add small library shim for Smithy client logging and middleware integration.
=> Client and Middleware Logging Support

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/EnumGenerator.java
=> Skip generating enum consts for enums without names

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/Waiters.java
Fixes vetting issue with generated waiter code.
=> Fixes vetting issue for waiter code

codegen/smithy-go-codegen-test/model/main.smithy, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ValidationGenerator.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/knowledge/GoValidationIndex.java
Adds support for validating union members that are part of a required trait chain.
=> Add support for validating union members in required trait chains.

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
Updates the smithy-go code generation version.
=> Update aws/smithy-go codegen version

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java, encoding/xml/xml_decoder_test.go, time/time.go, time/time_test.go, transport/http/middleware_content_length_test.go, transport/http/middleware_http_logging_test.go
=> updates smithy-go to v1.1.0

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ClientLogger.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/RuntimeClientPlugin.java
Addresses https://github.com/aws/aws-sdk-go-v2/pull/1138#discussion_r577943806
=> Adjust addConfigFieldResolver method name

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/Paginators.java
=> Fix paginator nil panic

CHANGELOG.md, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
* change log for v1.3.0 release
* update smithy go version
=> Adds change notes for smithy-go v1.3.0 go module release, and codegen update

CHANGELOG.md
=> Add changelog entry for release v1.3.1

codegen/smithy-go-codegen-test/build.gradle.kts
Updates smithy Gradle dependency to v0.5.3.
=> codegen: Update smithy gradle dependency

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
=> Fix serialization of enum types marked with payload trait

README.md
Adds build badge for GitHub actions to readme.
=> Add build badge to readme.

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ServiceGenerator.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ConfigField.java
Support for marking and documenting deprecated client config fields.
=> Support for marking and documenting deprecated client config fields.

CHANGELOG.md
Updates changelog for pending release changes.
=> Update changelog for pending release

CHANGELOG.md
Add CHANGELOG.md notes for upcoming v1.6.0 release
=> v1.6.0 Release

ptr/generate.go
* Handle error for defer close call
=> Handle error for defered file close call

document.go
=> Add Deperecation Notice to Document type

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpRpcProtocolGenerator.java
=> Fix Operation Path Bug

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/EndpointHostPrefixMiddleware.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/IdempotencyTokenMiddlewareGenerator.java
=> Ensure TopDownIndex is used when iterating service operations

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/Paginators.java
* Treat empty length string tokens as paginator last page condition.
* Honor initial starting token specified by the provided input parameters.
=> Paginator Improvements

codegen/gradle.properties, codegen/smithy-go-codegen-test/build.gradle.kts, codegen/smithy-go-codegen/build.gradle.kts
=> Pin Smithy dependencies versions to specific release

.changelog/cfe929e87e274e90b3f75bd020bb8cb2.json
=> Add Changelog Annotation

codegen/gradle.properties, codegen/settings.gradle.kts
Update to depend on latest version of `smithy` 1.21
=> Update smithy-go to smithy 1.21

.github/CODEOWNERS
Adds GitHub CODEOWNER so PR reviews can be auto assigned.
=> add GitHub code owner for auto assigned reviewers

codegen/smithy-go-codegen-test/model/main.smithy, codegen/smithy-go-codegen-test/model/more-nesting.smithy, codegen/smithy-go-codegen-test/model/nested.smithy, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenVisitor.java
N/A
---
Update to support mixins by applying the `flattenAndRemoveMixins()` transform (apply mixins and don't serialize mixin structures)
Also update `smithy-codegen-test/` to IDL 2.0 and to have a mixin codegen test.
---
*Testing:*
Ran `make smithy-clean smithy-build smithy-publish-local smithy-clean`.
Verified the diff builds in `smithy-codegen-test/` after adding the mixins test are expected (only build-info and model files have diffs, NO diffs in generated go code):
Diff: [`codegen/smithy-go-codegen-test/diff-build-mixin.diff`](https://github.com/syall/smithy-go/commit/3cee2f0d3d8e32ac1fdc4d3aec3aaccc473b1ecf#diff-30276b291acf515fd302adfc75ab3ae5b624d41f0646f776996ee87efdf325cd) 
```diff
--- …
```
=> Add support for Mixins

.github/workflows/codegen.yml, .github/workflows/go.yml
Update GitHub Actions for Go 1.19
=> Update GitHub Actions for Go 1.19

codegen/gradle.properties, codegen/smithy-go-codegen/build.gradle.kts
Adds a new gradle dependency on smithy-rules-engine for upcoming traits.
=> Add dependency on smithy-rules-engine for upcoming traits

README.md, encoding/xml/doc.go
=> Update links to point to smithy.io

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/AddOperationShapes.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenUtils.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolVisitor.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/Synthetic.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpRpcProtocolGenerator.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ProtocolGenerator.java, codegen/smithy-go-codegen/src/test/java/software/amazon/smithy/go/codegen/AddOperationShapesTest.java
Related to #287
Rename `SyntheticClone` to `Synthetic`.
=> Rename SyntheticClone to Synthetic

.github/CODEOWNERS
N/A
Fix CODEOWNERS for @aws/smithy
=> Fix CODEOWNERS for @aws/smithy

codegen/gradle.properties
N/A
---
Upgrade smithy to 1.27.2.
Tested with `make smithy-clean smithy-build smithy-publish-local`.
---
=> upgrade smithy to 1.27.2

.github/workflows/go.yml
N/A
Update CI to include Go 1.20 support
=> add go 1.20 to CI

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenVisitor.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/endpoints/EndpointParametersGenerator.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/endpoints/EndpointResolutionGenerator.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/endpoints/EndpointResolverGenerator.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/endpoints/EndpointTestsGenerator.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ProtocolGenerator.java, properties_test.go
Adds code generation of service-modeled endpoints2.0 resolution tests in the form of a single
=> Add endpoints2.0 tests codegen

properties.go, properties_test.go
N/A
Change `Properties` to a pointer receiver.
=> Change `Properties` to a pointer receiver

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/endpoints/EndpointMiddlewareGenerator.java, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/GoIntegration.java
Add a pre endpoints2.0 resolution hook for consumers
=> Add pre endpoint resolution hook for consumers

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/endpoints/EndpointResolverGenerator.java
Update the no rules matching message to be minimally workable.
=> Update the no rules matching error message

codegen/gradle.properties
=> Upgrade smithy core to latest

codegen/gradle.properties
=> Smithy upgrade

codegen/gradle.properties
=> update to smithy 1.45.0

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
Allow empty headers, as described on the updated, but not published protocol tests smithy-lang/smithy#2403
=> Allow all headers to be set to an empty value

.github/workflows/api_diff_check.yml, .github/workflows/codegen.yml, .github/workflows/go.yml, codegen/smithy-go-codegen-test/smithy-build.json, codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoModuleInfo.java, go.mod
=> Bump go version to 1.22

codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoSettings.java, codegen/smithy-go-codegen/src/test/java/software/amazon/smithy/go/codegen/ResolveProtocolTest.java
Adds SEP-based test cases for priority protocol selection.
=> test protocol selection

endpoints/endpoint.go
=> fix typo in comments

codegen/gradle.properties
Updating Smithy to latest version https://github.com/smithy-lang/smithy/releases/tag/1.62.0
Specially interested in the changes related to partitions
=> Update Smithy to 1.62.0
