aws/smithy-go

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoCodegenPlugin.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoDelegator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoDependency.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoModGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoWriter.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ImportDeclarations.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/StructureGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolVisitor.java
This adds dependency support and support for timestamps, big ints, and big decimals. The generated test package's types now looks like:
```go
import (
"time"
)
type CityCoordinates struct {
Latitude  *float32
Longitude *float32
}
type CitySummary struct {
Case   *string
CityId *string
Name   *string
Number *string
}
type GetCityImageInput struct {
CityId *string
}
type GetCityImageOutput struct {
Image []byte
}
type GetCityInput struct {
CityId *string
}
type GetCityOutput struct {
City        *CitySummary
Coordinates *CityCoordinates
Name        *string
}
type GetCurrentTimeOutput struct {
Time *time.Time
}
type GetForecastInput struct {
CityId *string
}
type GetForecastOutput struct {
ChanceOfRain *float32
}
type …
```
> Add support for dependencies and primitive shapes that require them

- codegen/smithy-go-codegen-test/model/main.smithy
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/MediaTypeGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolVisitor.java
- mediatype.go
This introduces an interface for media types, and generates types for shapes that use them. A string or byte array can have a `MediaType()` function that returns its media type, which is defined in an interface in the base package. Currently there's no special handling for any particular media type.
```go
import (
"time"
)
type CityCoordinates struct {
Latitude  *float32
Longitude *float32
}
type CityImageData []byte
func (m CityImageData) MediaType() string {
return "image/jpeg"
}
type CitySummary struct {
Case   *string
CityId *string
Name   *string
Number *string
}
type GetCityImageInput struct {
CityId *string
}
type GetCityImageOutput struct {
Image *CityImageData
}
type GetCityInput struct …
```
> Introduce MediaType support

- codegen/smithy-go-codegen-test/model/main.smithy
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/EnumGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolVisitor.java
This introduces enum generation. Enums are generated into `api_enums.go`, like so:
```go
type SimpleYesNo string
// Enum values for SimpleYesNo
const (
SimpleYesNoYes SimpleYesNo = "YES"
SimpleYesNoNo  SimpleYesNo = "NO"
)
type TypedYesNo string
// Enum values for TypedYesNo
const (
TypedYesNoYes TypedYesNo = "Yes"
TypedYesNoNo  TypedYesNo = "No"
)
```
> Generate enums

- codegen/smithy-go-codegen-test/model/main.smithy
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoDependency.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolVisitor.java
- document.go
This introduces an interface for document types, and ensures that their symbols are generated. A document type was introduced into the sample model for demonstrative purposes:
```go
import (
smithy "github.com/awslabs/smithy-go"
"time"
)
type CityCoordinates struct {
Latitude  *float32
Longitude *float32
}
type CitySummary struct {
Case   *string
CityId *string
Name   *string
Number *string
}
type GetCityImageInput struct {
CityId *string
}
type GetCityImageOutput struct {
Image []byte
}
type GetCityInput struct {
CityId *string
}
type GetCityOutput struct {
City        *CitySummary
Coordinates *CityCoordinates
Metadata    smithy.Document
Name        *string
}
type GetCurrentTimeOutput struct { …
```
> Introduce document type support

- errors.go
- fault.go
- middleware/step_deserialize.go
- middleware/step_finalize.go
- middleware/step_initialize.go
- middleware/step_serialize.go
- transport/http/response.go
- transport/http/response_error_example_test.go
Adds the base error and metadata wrapping error types that Smithy SDKs will use to compose APIErrors received from API responses with additional metadata.
Smithy generated SDK API errors will implement a common smithy APIError interface. This interface provides generic accessor methods that all generated client API errors, will implement. Metadata about the operation, response, retry, etc will all be provided by error types
wrapping the returned APIError value. This allows the SDK to use errors across multiple protocols like HTTP and event stream without additional noise. This approach also protects the SDK against additional metadata fields being added to the chain forcing the SDK to use either optional interfaces, or breaking change to expose the new metadata.
Layering errors this way …
> Add Smithy APIError base and wrapping error types

- middleware/metadata.go
- middleware/middleware_test.go
- transport/http/deserailize_example_test.go
- transport/http/response_error_example_test.go
- transport/http/serialize_example_test.go
Updates the middleware Metadata type to be pass by value as a structure in the middleware instead of interface. This removes the need from middleware writers to use `NewMetadata` each time an error is handled. This does require the helper methods to use the Metadata pointer for
set, and MetadataReader for Gets.
> Update middleware Metadata to be a struct instead of interface

- transport/http/request.go
- transport/http/serialize_example_test.go
Adds SetStream and Rewind functionality to the HTTP Request transport structure. Additionally modified the methods to only take a context when constructing the final request with `Build`
> Add SetStream and RewindStream to HTTP Request Transport

- codegen/smithy-go-codegen-test/build.gradle.kts
- codegen/smithy-go-codegen-test/model/main.smithy
- codegen/smithy-go-codegen-test/model/more-nesting.smithy
- codegen/smithy-go-codegen-test/model/nested.smithy
- codegen/smithy-go-codegen/build.gradle.kts
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/DocumentationConverter.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/EnumGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoWriter.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/MediaTypeGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/StructureGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/UnionGenerator.java
- codegen/smithy-go-codegen/src/test/java/software/amazon/smithy/go/codegen/DocumentationConverterTest.java
This updates the code generator to output shape documentation, converting it from commonmark to godoc. This required some functionality from the 0.10 branch of Smithy. While that should release soonish, in the meantime you'll need to build and publish locally from that branch to build.
[Existing tests](https://github.com/aws/aws-sdk-go-v2/blob/master/private/model/api/docstring_test.go) from the go-based converter were ported over to make sure everything is still ship-shape. The only real difference is that it doesn't currently wrap lines.
> Write out shape documentation

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoDependency.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolVisitor.java
*Description of changes:* Separates the concept of a "source path" that is used for declaring a go.mod dependency versus an "import path" of a package within the given dependency.
Similar to how Java jars can contain multiple class namespaces, a Go module/repository can contain multiple packages at different import paths within.
> Add concept of source/module path versus import path

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolVisitor.java
Since enum values can't be a length == 0 string (empty value), Enums should not be generated as pointer type members.
> Generate enum member types as values

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoDependency.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/StructureGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolVisitor.java
This adds error generation. The errors are produced as interfaces in order to support inheritance.
```go
import (
"fmt"
smithy "github.com/awslabs/smithy-go"
)
// Error encountered when no resource could be found.
type NoSuchResourceInterface interface {
smithy.APIError
isNoSuchResource()
ErrorMessage() string
ErrorFault() string
ErrorCode() string
// The type of resource that was not found.
GetResourceType() string
// HasResourceType returns whether ResourceType exists.
HasResourceType() bool
}
// The concrete implementation for NoSuchResourceInterface. This should not be used directly.
type NoSuchResource struct {
Message *string
ResourceType *string
}
func (e *NoSuchResource) Error() string { …
```
> Generate error interfaces and structures

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolVisitor.java
This moves generated types for most shapes into a "types" namespace.
This allows for things like synthesized types for operation input /
output without risk of conflicting names.
As part of this a symbol is generated for the service shape (client)
to enable generating an empty file for the client. This is needed as
otherwise `go fmt` will complain about an empty package.
The generated module will now look like:
```
├── api_client.go
├── go.mod
└── types
├── enums.go
├── errors.go
└── types.go
```
> Move types into their own namespace

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoStackStepMiddlewareGenerator.java
Fixes a bug in the middleware generator that resulted in the handler contents being written into the structure field definition.
> Fix middleware generator bug

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenUtils.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoDependency.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoStackStepMiddlewareGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoWriter.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/StructureGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolUtils.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolVisitor.java
This updates and fixes the way namespacing is handled, particularly
with regard to aliasing. Previously a SymbolReference was being
created to represent the namespace, but that isn't right since a
namespace isn't an individually referenceable entity. Now the symbol
itself controls how its namespace should be referenced. This ends up
being much more concise to define as an added bonus.
> Update namespace handling

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenUtils.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoDependency.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ProtocolGenerator.java
* Adds support for deserializer generation for "rest" bindings of operation shapes. 
Generated deserializers.go for lex-runtime:
```go
package lexruntimeservice
import (
"fmt"
"github.com/aws/aws-sdk-go-v2/service/lexruntimeservice/types"
smithyhttp "github.com/awslabs/smithy-go/transport/http"
)
func awsRestjson1_deserializeHttpBindingsPutSessionOutput(v *types.PutSessionOutput, response *smithyhttp.Response) error {
if v == nil {
return fmt.Errorf("unsupported deserialization for nil %T", v)
}
if val := response.Header.Get("Content-Type"); val != "" {
v.ContentType = &val
}
if val := response.Header.Get("x-amz-lex-dialog-state"); val != "" {
v.DialogState = types.DialogState(val)
}
if val := …
```
> HttpBinding Deserialization Support

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoDependency.java
Adds const version variables to for defined dependencies. Since the
generated code cannot depend on multiple minor versions of a module at
using const variables help keep the dependency definitions consistent.
> Add const versions for dependencies.

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoWriter.java
Adds a default wrap length to generated doc strings to improve generated
code documentation's readability.
> Add wrapping generated doc string to a fixed length

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/OperationGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ServiceGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/StructureGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/GoIntegration.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/RuntimeClientPlugin.java
This is a draft of client generation, based on https://github.com/aws/aws-sdk-go-v2/pull/530
Outside of that the only real gap is the lack application protocol handling, which will be necessary to set some config defaults and to initialize the middleware stack.
A generated service currently looks like:
```go
import (
"github.com/awslabs/smithy-go/middleware"
smithyhttp "github.com/awslabs/smithy-go/transport/http"
)
// Provides weather forecasts.
type Client struct {
options Options
}
// New returns an initialized Client based on the functional options.
// Provide additional functional options to further configure the behavior
// of the client, such as changing the client's endpoint or adding …
```
> Generate clients

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoDependency.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
* Adds more simple types to work with protocol-test generation
* Fixes bug causing incorrect go code gen.
> `HttpBindingProtocolGen`: fixes Http binding deserializer bug

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/StructureGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolVisitor.java
This removes generation of error interfaces. Instead, when inheritance
is added we will make heavy use of error.As to get less specific
types.
Example generated error:
```go
package types
import (
"fmt"
smithy "github.com/awslabs/smithy-go"
)
// Error encountered when no resource could be found.
type NoSuchResource struct {
Message *string
ResourceType *string
}
func (e *NoSuchResource) Error() string {
return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *NoSuchResource) ErrorMessage() string {
if e.Message == nil {
return ""
}
return *e.Message
}
func (e *NoSuchResource) ErrorCode() string { return "NoSuchResource" }
func (e *NoSuchResource) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }
func (e …
```
> Remove error interfaces

- codegen/smithy-go-codegen-test/build.gradle.kts
- codegen/smithy-go-codegen-test/model/main.smithy
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoDependency.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/OperationGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/StructureGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolUtils.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolVisitor.java
This adds support for the `streaming` trait on blob shapes. An `io.Reader` will be generated on input and an `io.ReadCloser` will be generated on output.
This also updates the test service to not depend on AWS traits, adding a faux protocol complete with a handful of protocol tests. It also adds event streams and references to shapes that weren't referenced before.
> Add support for binary streams

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoWriter.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolUtils.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolVisitor.java
Fixes the generation of maps and slices when nested in other map or slice types.
```go
type KitchenSink struct {
Blob *[]byte
Boolean *bool
Double *float64
EmptyStruct *EmptyStruct
Float *float32
HttpdateTimestamp *time.Time
Integer *int32
Iso8601Timestamp *time.Time
JsonValue *string
ListOfLists [][]*string
ListOfMapsOfStrings []map[string]*string
ListOfStrings []*string
ListOfStructs []*SimpleStruct
Long *int64
MapOfListsOfStrings map[string][]*string
MapOfMaps map[string]map[string]*string
MapOfStrings map[string]*string
MapOfStructs map[string]*SimpleStruct
RecursiveList []*KitchenSink
RecursiveMap map[string]*KitchenSink
RecursiveStruct *KitchenSink
SimpleStruct *SimpleStruct
String_ *string
StructWithLocationName *StructWithLocationName
Timestamp *time.Time
UnixTimestamp *time.Time …
```
> Fix nested slice and map shape generation

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/OperationGenerator.java
Fixes the check used for synthetic shapes, as generated input/output shapes for operations that did not model them were incorrectly being generated into the types package.
> Fix issue with empty synthetic type generating into types package.

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolVisitor.java
Originally a smithy byte shape was being generated as a Go byte, which is a type alias of a unit8. This change will now generate Smithy byte shape as a int8.
> Generate Smithy byte as Go int8

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoDependency.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
GoDependency was referring to the wrong import path for SDK's private/protocol package.
> Fixup private/protocol import path in GoDependency

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolVisitor.java
The SymbolVisitor was improperly detecting synthetic shapes when they
were generated fresh rather than being clones of existing shapes.
Now the namespace of the shape is checked rather than the presence of
the synthetic clone trait.
> Fix bug placing some I/O shapes in the wrong file

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoDependency.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ProtocolGenerator.java
* Adds rest json deserializer generation support
* Adds rest json deserializer middleware generation support
Related to aws/aws-sdk-go-v2#568
> Adds document binding deserializers and middleware generation support

- codegen/smithy-go-codegen-test/build.gradle.kts
- codegen/smithy-go-codegen/build.gradle.kts
This updates the dependencies on smithy to use a range across the
current minor version. This will let us pick up any new patch
versions without having to manually update every time.
Range dependencies can be very dangerous, but in this case it's only
on a dependency that we control and the range is fairly tight.
> Use version ranges for Smithy dependencies

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoDependency.java
Fixes the gofmt failing because of the go.mod not defining the API client's module yet.
Also updates smithy-go pkg dependency to be `latest` until smithy releases a tagged version. Non-existent tagged version breaks gofmt/gomod.
> Swap go.mod and gofmt execution so module is created first.

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
Fixes up code generation errors preventing client from compiling.  Updates deserialization functions to use pointer input for map/lists instead of being asymetric with structures.
> Fixup code generation compile errors

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
* Adds missing document shape deserializers for shapes referenced only by error shapes.
> Generate deserializers for document shapes referred by error shapes 

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
* fixup API client code generation compile errors for type assignments.
* add stubbing out output in case unused
> fixup API client code generation compile errors for type assignments.

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoDependency.java
Sets the Smithy codegen's SDK and smithy-go versions to explicit go.mod hash. This works around the issue of smithy-go's dependencies referring to a version of the SDK that doesn't include the smithy codegen behavior.
> Use SDK Smithy branch for Smithy codegen

- transport/http/request.go
Fixes the initialization of smithy.Request to handle empty body correctly.
> transport/http: Fix initialization of smithy Request

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/OperationGenerator.java
- errors.go
Updates the API client's operation methods to wrap the middleware stack returned error with the smithy OperationError value annotating service and operation the error came from.
```go
handler := middleware.DecorateHandler(smithyhttp.NewClientHandler(options.HTTPClient), stack)
result, metadata, err := handler.Handle(ctx, params)
if err != nil {
return nil, &smithy.OperationError{
ServiceID:     c.ServiceID(),
OperationName: "AllQueryStringTypes",
Err:           err,
}
}
out := result.(*AllQueryStringTypesOutput)
out.ResultMetadata = metadata
return out, nil
```
> Update Operation to wrap error with smithy operation error

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ApplicationProtocol.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenUtils.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoDependency.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoStackStepMiddlewareGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoWriter.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/OperationGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ServiceGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/StructureGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolUtils.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
- codegen/smithy-go-codegen/src/test/java/software/amazon/smithy/go/codegen/GoDependencyTest.java
- time/time.go
- time/time_test.go
This PR refactors the GoDependency type and constants in order to decouple AWS specific dependencies from the smithy repository.
> Refactor GoDependency and Dependency Constants

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ServiceGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ConfigField.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/GoIntegration.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/RuntimeClientPlugin.java
This changes the way that client config options are added. Now a `RuntimeClientPlugin` can register a number of fields to add to a config. Each option will be added to that config, and a getter will be generated to enable creating interfaces.
For example:
```java
@Override
public List<RuntimeClientPlugin> getClientPlugins() {
return ListUtils.of(RuntimeClientPlugin.builder()
.addConfigField(ConfigField.builder()
.name("MyConfig")
.type(SymbolUtils.createPointableSymbolBuilder("int64")
.putProperty(SymbolUtils.GO_UNIVERSE_TYPE, true)
.build())
.documentation("My config")
.build())
.build());
}
```
```go
type Options struct {
// Set of options to modify how an operation is invoked. These apply to all
// operations invoked for this client. Use functional options on …
```
> Add config field interface to RuntimeClientPlugin

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolUnitTestGenerator.java
Updates the generated protocol test client initialization to not expect a error return parameter from the client's New function.
> Fixup protocol test client initialization to not expect error

- .travis.yml
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenUtils.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/StructureGenerator.java
Adds go build to the set of commands run after the code generation completes. This ensures that the generated code compiles. Both test and regular code.
Fixes up error shape generation so that exception getters methods return the expected type and use the smithy-go/ptr pkg for converting scalar pointers to values.
> Add Go build to finalize codegen step, and fixup error generation

- codegen/smithy-go-codegen-test/build.gradle.kts
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenVisitor.java
Removes explicit go compile check for all smithy-go generated clients. Moves the validation into the `smithy-go-codegen-test` module to validate that the individual test compiles.
All other generated client validation in `aws-sdk-go-v2` is handled via coping from their generated output locations, and validated via the SDK's make tasks.
> remove explicit go compile check from smithy-go

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
Fixes the bug with protocol tests failing because the streaming body was always nil. This ensures that the updated request value is always added back to the input for passing down to the next handler.
> fix setting stream not updating request

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolUnitTestRequestGenerator.java
Modifies Smithy code generation to correctly validate URI encoding using `RawPath` rather then `Path`.
> Update protocol tests to validate RawPath

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
- httpbinding/encode.go
- httpbinding/encode_test.go
Changes the HTTP Binding encoder design to avoid issues with referencing potentially out of date references to `net/http.Request` types.
> HTTP Binding Encoder Changes

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/IdempotencyTokenMiddlewareGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ValidationGenerator.java
Adds sorting order to GoIntegrations to help improve consistent code generation order.
> Add sort order to implementations of GoIntegrations

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolUnitTestGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolUnitTestRequestGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolUnitTestResponseGenerator.java
Refactors protocol test body breaking it up into multiple segments `setup`, `test server`, `test client`, and `client operation` This allows for more fine grained overriding of the protocol tests's generated code and behavior.  
Adds a test HTTP server to the protocol tests to exercise more real world request serialization/deserialization behavior.
> Refactor protocol test body to use test server to validate http request

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolUnitTestRequestGenerator.java
Fixes regression in HTTP protocol test's handling of request URL path vs raw path. The Go HTTP server does not set request's URL.RawPath value if the received request message's Path does not contain escaping. Fixes this by setting RawPath if unset.
> fixup HTTP protocol test handling of request URL path vs raw path

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/OperationGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/GoIntegration.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/IdempotencyTokenMiddlewareGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/MiddlewareRegistrar.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/RuntimeClientPlugin.java
- transport/http/retry.go
* Adds a runtime client plugin to register middlewares on stack.
* Middlewares can now be registered both inline or using middleware helper functions.
* Updates IdempotencyToken middleware generation logic to use a value provider interface. 
* Updates to work with new client option getters
* Related to aws/aws-sdk-go-v2#596
> Refactors middleware addition to stack

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/OperationGenerator.java
* Fix bug that rendered serde middleware as string when adding in middleware stack
> fix bug that rendered serde middleware as string when adding in middleware stack

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolUnitTestGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/IdempotencyTokenMiddlewareGenerator.java
- codegen/smithy-go-codegen/src/main/resources/META-INF/services/software.amazon.smithy.go.codegen.integration.GoIntegration
* Temporarily removes idempotency token middleware Integration to fix failing master
* Pairs with https://github.com/aws/aws-sdk-go-v2/pull/620
> Removes idempotency token middleware addition

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
- httpbinding/encode.go
- httpbinding/encode_test.go
Adds an additional method to Encoder to determine if a header has been set.
> Add HasHeader to rest Encoder to check if a header value has been set

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
Updates how HTTP header bindings are generated for (de)serialization to correctly serialize and deserialize header prefix, header values, and lists. 
> Fixup header value, list, and prefix (de)serialization

- transport/http/client.go
Adds a utility to the HTTP transport to wrap an HTTP client with wire logging of the request and response.
> Add wrapper utility for logging HTTP client request/responses

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolUnitTestGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/IdempotencyTokenMiddlewareGenerator.java
- codegen/smithy-go-codegen/src/main/resources/META-INF/services/software.amazon.smithy.go.codegen.integration.GoIntegration
Re-enables the Idempotency token auto fill middleware and add Client config Option for the token provider. Removes unused protocol testing code that was moved to the SDK's config option overrides.
Java half of https://github.com/awslabs/smithy-go/pull/102
Related to https://github.com/aws/aws-sdk-go-v2/pull/628
> Re-enable idempotency token middleware behavior

- io/ringbuffer.go
- io/ringbuffer_test.go
* Adds a Reset method to ring Buffer utility in `io` package.
> `io`: adds Reset method to io ringbuffer

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ShapeValueGenerator.java
Fixes the generated protocol tests to correctly generate Go type values for shapes nested within nested list, structs, and maps. The generation was incorrectly initializing the nested shape, before assigning in inner value of nil.
Example codegen diff
```diff
--- a/internal/protocoltest/awsrestjson/api_op_JsonMaps_test.go
+++ b/internal/protocoltest/awsrestjson/api_op_JsonMaps_test.go
@@ -70,8 +70,7 @@ func TestClient_JsonMaps_awsRestjson1Serialize(t *testing.T) {
"RestJsonSerializesNullMapValues": {
Params: &JsonMapsInput{
MyMap: map[string]*types.GreetingStruct{
-                                       "foo": {
-                                               nil},
+                                       "foo": nil,
},
},
ExpectMethod:  "POST",
@@ -206,8 +205,7 @@ func …
```
> Fix protocol test generation for nested shape null values

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoStackStepMiddlewareGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/IdempotencyTokenMiddlewareGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ValidationGenerator.java
- codegen/smithy-go-codegen/src/test/java/software/amazon/smithy/go/codegen/GoStackStepMiddlewareGeneratorTest.java
Updates the helpers for generating SDK middleware in a client package to separate the middleware name from the ID. The SDK generated middleware generic names were added.
This change does not create constants or other methods of organizing the IDs.
> Update SDKs middleware generation utils to separate name from id

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/DocumentShapeDeserVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/DocumentShapeSerVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolGeneratorUtils.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpRpcProtocolGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ProtocolGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ProtocolUtils.java
This add support for http rpc protocols. There is some refactoring work done here, mostly in ProtocolUtils, to reduce copied code, but existing code is as of yet still intact.
related: https://github.com/aws/aws-sdk-go-v2/pull/599
> Support HTTP RPC protocols

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolUnitTestRequestGenerator.java
- transport/http/middleware_content_length.go
- transport/http/middleware_content_length_test.go
- transport/http/request.go
Adds middleware that will set the HTTP request's Content-Length header if the length of the serialized stream can be determined. If the length cannot be determined or the Header value is already set the middleware will do nothing.
Fails the request if the underlying request stream reader is seekable but fails to seek.
> Add middleware to set HTTP request content length

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
Updates the smithy-go Go module dependency hash to be the latest version.
> Update smithy-go Module dependency

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
Exposes the static construction functions for creating standard library dependencies.
> Expose standard library GoDependency static construction methods.

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolGeneratorUtils.java
- testing/document.go
- testing/document_test.go
This implements `URLFormEqual`, which is needed to run protocol tests for query. I also slipped in a minor change to the shared http error gen to not import smithyio since it isn't used there.
It's a flat comparison, so things like Query's maps are flattened out, but the output is still useful:
```
=== RUN   TestAssertURLFormEqual/not_equal
TestAssertURLFormEqual/not_equal: document_test.go:60: expect form to be equal, Query mismatch (-expect +actual):
  url.Values{
  	"Action":               {"QueryMaps"},
  	"MapArg.entry.1.key":   {"foo"},
  	"MapArg.entry.1.value": {"Foo"},
- 	"MapArg.entry.2.key":   {"bar"},
- 	"MapArg.entry.2.value": {"Bar"},
  	"Version":              {"2020-01-08"},
  }
```
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …
> Implement URLFormEqual

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ProtocolUtils.java
This refactors the rest protocol generator to use more of the shared code, notably error deserialization. It also updates the abstract methods to take `GenerationContext` where appropriate.
related: https://github.com/aws/aws-sdk-go-v2/pull/644
> Refactor http binding protocol generator

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ShapeValueGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolUnitTestGenerator.java
- io/reader.go
- testing/struct.go
- testing/struct_test.go
Fixes the generation of protocol tests with streaming input and output members. Refactors the comparison of structure values to use a utility that flexibly compares the io.Reader values. Allowing the underlying io.Reader implementations to be different types, but compare as equal if the contents of the readers are the same.
> Fix protocol test generation for streaming types

- httpbinding/encode.go
- httpbinding/query.go
- httpbinding/query_test.go
- testing/document.go
- testing/document_test.go
This updates the url form equal function to strip out insignificant whitespace, which is whitespace that is not percent encoded.
I've also updated `NewQueryValue` to be exported so it can be used in the query serializer.
Needed for: https://github.com/aws/aws-sdk-go-v2/pull/652
> Strip insignificant whitespace from form bodies and export NewQueryValue

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenUtils.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
- transport/http/headerlist.go
- transport/http/headerlist_test.go
Adds support for the HTTP Date timestamp format shapes within header lists, and header prefix lists. Updates the deserialize codegen to split header list values on comma separated values.
Update deserialize header codegen to use member shape instead of target shape
> Add support for header list of timestamp HTTP Date format

- .travis.yml
Updates Travis CI tests to include Go 1.15.
> Add Go tip and Go 1.15 to CI tests

- httpbinding/path_replace.go
Exposes `httpbinding.EscapePath` for usage in the AWS SigV4 implementation.
> Expose httpbinding.EscapePath

- middleware/step_build.go
- middleware/step_deserialize.go
- middleware/step_finalize.go
- middleware/step_initialize.go
- middleware/step_serialize.go
- transport/http/middleware_content_length_test.go
Adds Step HandlerFunc types that allow wrapping functions to satisfy a step middleware's HandlerFunc interface.
> Adds Step HandlerFunc types that allow wrapping functions to satisfy a step middleware's HandlerFunc interface

- middleware/step_build.go
- middleware/step_deserialize.go
- middleware/step_finalize.go
- middleware/step_initialize.go
- middleware/step_serialize.go
Don't attempt to cast to the middleware type if a Get returned with no ID found.
> Don't cast to middleware type if failed to retrieve ID

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
- internal/encoding/encoding.go
- json/value.go
- testing/bytes.go
- testing/document.go
- testing/document_test.go
- testing/xml/doc.go
- testing/xml/sort.go
- testing/xml/sort_test.go
- testing/xml/xmlToStruct.go
- xml/array.go
- xml/array_test.go
- xml/constants.go
- xml/doc.go
- xml/element.go
- xml/encoder.go
- xml/encoder_test.go
- xml/escape.go
- xml/map.go
- xml/map_test.go
- xml/value.go
- xml/value_test.go
* Adds the XML encoder to help serialize xml documents.
* Adds an assert-xml library to compare two xml documents. 
> add xml encoder, assert-xml util for xml document serialization

- json/decoder_util.go
- json/decoder_util_test.go
This moves some of the json decoder utilities over from the sdk repo, namely the utilities to discard or collect unknown values.
> Add json decoder utils

- transport/http/middleware_headers.go
- transport/http/middleware_headers_test.go
Adds `AddHeaderValue` and `SetHeaderValue` stack mutators that allow easy manipulation of HTTP request headers.
> Add Header Helper Middleware

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/OperationGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ServiceGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/GoIntegration.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolUnitTestResponseErrorGenerator.java
- errors.go
- httpbinding/encode.go
- httpbinding/encode_test.go
- transport/http/middleware_content_length.go
- transport/http/middleware_content_length_test.go
Fixes the Content-Length behavior by correctly utilizing the net/http.Request member for setting the value. The header value if set directly is ignored by the standard library. This was a regression from the original AWS SDK for Go V1/V2 behavior.
> Fix Content-Length Behavior; Define GoIntegration for ServiceId

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
- middleware/ordered_group.go
- middleware/ordered_group_test.go
- middleware/shared_test.go
- middleware/stack.go
- middleware/stack_test.go
- middleware/step_build.go
- middleware/step_deserialize.go
- middleware/step_finalize.go
- middleware/step_initialize.go
- middleware/step_serialize.go
Adds unit tests for the middleware ordering behavior, this discovered abug in the Insert After behavior not correctly inserting within a list. It only inserted after to the end of the list.
Also adds a List method for all middleware step that returns the list of middleware in the step.
Reduce allocations for getting order of middleware when middleware stack is built into handler decorators.
>  Fix Insert After relative ordering, added unit tests

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/IdempotencyTokenMiddlewareGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ProtocolGenerator.java
Fixes issues with the API client codegen that were discovered in the latest set of models added to the SDK.
* Makes idempotency used helper public, needed by https://github.com/aws/aws-sdk-go-v2/pull/708.
* Fixes #166 by removing leading underscores from shape and member names. Since underscore is not a `capital` alphabetic character, making the type or member unexported.
* Fixes #167 by ensuring operation input/output shape (de)serializers are generated with unique name vs modeled shape (de)serializer functions.
> Fix API client generation issues discovered in new model builds

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
- io/ringbuffer.go
Adds a `Bytes` method to the `RingBuffer` to make it easier to retrieve the value of its buffer.
> Add Bytes method to RingBuffer

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
- httpbinding/encode.go
- httpbinding/encode_test.go
- httpbinding/header.go
- httpbinding/header_test.go
- middleware/middleware.go
- middleware/middleware_test.go
- middleware/step_build.go
- middleware/step_deserialize.go
- middleware/step_finalize.go
- middleware/step_initialize.go
- middleware/step_serialize.go
- rand/uuid.go
- transport/http/user_agent.go
Makes some small performance fixes my removing the `RecordMiddleware`, removing usage of `fmt.Sprintf`, precomputing canonical headers and setting them directly via the `httpbinding.Encoder`, and moving the `RingBuffer`'s backing slice to the stack.
> Performance fixes

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolUnitTestGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolUnitTestResponseGenerator.java
This removes the test server for response tests, replacing it with
a simple stubbed HTTP client that returns a pre-canned response.
This is necessary because the test server would inject additional
headers / info that we weren't expecting which would break protocol
tests where we have an expectation on the entire set of headers.
This will need to go along with a PR in the aws repo.
> Don't use test server for response tests

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
- transport/http/response.go
- transport/http/response_error_example_test.go
Adds HttpStatusCode() for ResponseError type. updates example usage
> adds HttpStatusCode() for ResponseError type. updates example usage

- transport/http/request.go
- transport/http/request_test.go
Updates the smithy-go http request type's RewindStream method to not fail if the request does not have a body. The Rewind becomes a no-op. Without this change, nil streams of requests would cause the request's RewindStream method to fail.
> A request without a body should not fail request rewind stream

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
- errors.go
- transport/http/client.go
- transport/http/client_test.go
Adds wrapping the HTTP client handler's response with an `RequestSendError` for all HTTP request send errors, and `CanceledError` if the context passed in to the handler was canceled and the HTTP client encountered an error.
> Add RequestSendError And CanceledError to HTTP ClientHandler

- codegen/README.md
The java version in the readme was wrong, so I fixed it and added a bit about the minimum go version.
> Fix version numbers in readme

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolGeneratorUtils.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpRpcProtocolGenerator.java
- transport/http/client.go
- transport/http/host.go
- transport/http/host_test.go
- transport/http/request.go
This adds support for the endpoint and hostLabel traits. This is
accomplished by adding a `HostPrefix` member to the Smithy Request
struct, which is prepended to the host when the underlying http
Request is finalized.
If there are no labels, the host prefix is simply generated as a
a string that is set on the smithy request like so:
```go
request.HostPrefix = "data-"
```
If there are labels, a string builder is used:
```go
var prefix strings.Builder
prefix.WriteString("data-")
if input.ServiceName == nil {
return out, metadata, &smithy.SerializationError{Err: fmt.Errorf("ServiceName forms part of the endpoint host and so may not be nil")}
} else if !smithyhttp.ValidateHostLabel(*input.ServiceName) {
return out, metadata, &smithy.SerializationError{Err: fmt.Errorf("ServiceName forms part …
```
> Support endpoint and hostLabel traits

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
Update Smithy code generation to use smithy-go at v0.1.0.
> Update Smithy Dependency to v0.1.0

- ptr/generate.go
- ptr/to_ptr.go
- ptr/to_ptr_test.go
related to https://github.com/aws/aws-sdk-go-v2/issues/777
back port of https://github.com/aws/aws-sdk-go-v2/pull/778
all members of the slice point same address.
https://play.golang.org/p/FUBdYewJvLH
```go
package main
import (
"fmt"
)
func StringSlice(vs []string) []*string {
ps := make([]*string, len(vs))
for i, v := range vs {
ps[i] = &v
}
return ps
}
func main() {
r := StringSlice([]string{"abc", "def"})
fmt.Printf("%p\n", r[0])
fmt.Printf("%p\n", r[1])
//Output:
//0xc0000961f0
//0xc0000961f0
}
```
```go
for i, v := range vs {
v := v // NEEDS THIS LINE
ps[i] = &v
}
```
> fix to_ptr address

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
- ptr/doc.go
- ptr/gen_scalars.go
- ptr/generate.go
Adds exporting the pointer types when the `codegen` build flag is present for the `ptr` package. This allows the v2 SDK to generate wrappers around these shared definition of the types generated.
Related to https://github.com/aws/aws-sdk-go-v2/pull/778, https://github.com/aws/aws-sdk-go-v2/pull/781, and https://github.com/awslabs/smithy-go/pull/191
> ptr: Expose pointer types for codegen

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/StructureGenerator.java
Removes error type accessor methods from generated error types. With the `errors.As` design these are not needed.
> codegen: Remove error type accessor methods

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/StructureGenerator.java
Updates the struct member code generation to add whitespace between members to improve their readability.
```go
// Creates an archive rule.
type CreateArchiveRuleInput struct {
+
// The name of the created analyzer.
AnalyzerName *string
+
// The name of the rule to create.
RuleName *string
+
// The criteria for the rule.
Filter map[string]*types.Criterion
+
// A client token.
ClientToken *string
}
```
> codegen: Add whitespace between struct members

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoWriter.java
Adds documentation to state the member is required in the generated structures.
```go
type CreateGroupInput struct {
// The case-sensitive name of the new group. Default is a reserved name and names
// must be unique.
+       //
+       // This member is required.
GroupName *string
```
> Add documenation of requirement members.

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolGeneratorUtils.java
Fixes the transport/http#ValidHostLabel function's reference in codegen.
> codegen: Fix ValidHostLabel reference in codegen

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenUtils.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/StructureGenerator.java
Updates the struct codegen to sort struct members by required first and alphabetic next. This updates the struct codegen to list required members before optional members in an API.
```diff
type CreateAnalyzerInput struct {
// The name of the analyzer to create.
//
// This member is required.
AnalyzerName *string
// The type of analyzer to create. Only ACCOUNT analyzers are supported. You can
// create only one analyzer per account per Region.
//
// This member is required.
Type types.Type
// Specifies the archive rules to add for the analyzer. Archive rules automatically
// archive findings that meet the criteria you define for the rule.
ArchiveRules []*types.InlineArchiveRule
-       // The tags to apply to the analyzer.
-       Tags map[string]*string
// A client token.
ClientToken …
```
> codegen: Sort struct members by required and alphabetic order

- codegen/smithy-go-codegen-test/build.gradle.kts
- codegen/smithy-go-codegen/build.gradle.kts
This updates the minimum smithy versions to the latest minor versions. We need to bump this for the http status code binding, but also this release fixes a number of bugs that would prevent building on Windows.
> Update minimum smithy versions

- codegen/smithy-go-codegen-test/model/main.smithy
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenUtils.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/trait/UnexportedMemberTrait.java
Adds support for generating unexported members into an API model's structure shapes. This allows unexported members to be injected into the structure shapes.
Adds utility to expect a member by name or predicate in a structure shape.
> codegen: Add support for codegen adding unexported members to api structure shape

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/OperationGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ServiceGenerator.java
Updates the API client code generation to provide a `invokeOperation` method that performs the majority of heavy lifting done by the operation.
This also allows future customizations like PresignedURL to take advantage of the invoke operation while changing the response type to a presigned URL value.
> codegen: Update API client codegen to share operation invoke behavior

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/AddChecksumRequiredMiddleware.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ChecksumRequiredMiddlewareGenerator.java
- codegen/smithy-go-codegen/src/main/resources/META-INF/services/software.amazon.smithy.go.codegen.integration.GoIntegration
- transport/http/checksum_middleware.go
- transport/http/checksum_middleware_test.go
- transport/http/md5_checksum.go
* Adds an integration to use `httpChecksumRequiredTrait` for operations that require Content-MD5 header. 
> add support for checksum required trait

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
* `make generate` on aws sdk go v2 supports go pseudo hashes.
* Updates smithy go dependency used by aws sdk for go v2 sdk to use pseudo go hash
> update smithy go dependency constant to be pseudo hash

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoCodegenPlugin.java
Adds support for a new environment variable `SMITHY_GO_BUILD_API` that allows you to specify a comma(`,`) deliminated set of `serviceId`s of API model that should be built.
The projections for the models will still be invoked since that is done in smithy core, but the smithy-go build of the model will be skipped for all service Ids not in the list.
Example using aws-sdk-go-v2 to build a single API client.
```sh
SMITHY_GO_BUILD_API="com.amazonaws.rds#AmazonRDSv19,com.amazonaws.ec2#AmazonEC2" make smithy-build gen-repo-mod-replace
```
> codegen: Add option to build select API models, instead of all

- codegen/smithy-go-codegen/build.gradle.kts
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/DocumentationConverter.java
- codegen/smithy-go-codegen/src/test/java/software/amazon/smithy/go/codegen/DocumentationConverterTest.java
This fixes two documentation formatting issues:
1. It fixes an issue where some HTML block were being interpreted as code blocks due to liberal use of indentation. It does this by disabling the indented code block parsing entirely, which seems like an acceptable trade since commonmark allows fenced code blocks that people tend to prefer in my experience.
2. It fixes an issue where anchors without references were being rendered.
> Fix doc formatting

- transport/http/internal/io/safe.go
- transport/http/internal/io/safe_test.go
- transport/http/request.go
Wraps the request body io.ReadCloser in a safe io.ReadCloser that will not retain references to the underlying reader after close has been called. Supports exposing `WriteTo` interface method if support by the `io.ReadCloser` type. This allows for `io.Copy(dst, src)` to take advantage of this if the optimization is available on the type.
> Wrap request bodies in safe reader to prevent data race conditions.

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
* Adds a check for input member to not be empty when targeting URI label
> add validation for input member to not be empty for URI label encoding

- middleware/ordered_group.go
- middleware/ordered_group_test.go
- middleware/step_build.go
- middleware/step_deserialize.go
- middleware/step_finalize.go
- middleware/step_initialize.go
- middleware/step_serialize.go
Adds support for pre-configuring slot identifiers that middleware can use for inserting / adding themselves to a step.
> Add Support for Slots to Stack Steps

- middleware/doc.go
Cleans up the `doc.go` file's bullet points for better go doc presentation.
> middleware: cleanup doc.go usage of bullet points

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/EndpointHostPrefixMiddleware.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolGeneratorUtils.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpRpcProtocolGenerator.java
- codegen/smithy-go-codegen/src/main/resources/META-INF/services/software.amazon.smithy.go.codegen.integration.GoIntegration
- transport/http/middleware_metadata.go
Adds a new `HostnameImmutable` context value getter/setter helpers to `transport/http` package. 
Updates EndpointTrait's HostPrefix handling to use the HostnameImmutable to skip modifying the endpoint.
Also refactors EndpointTrait HostPrefix handling to be an integration instead of implemented directly in the operation serializer.
> Add HostnameImmutable context value for middleware

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/DocumentationConverter.java
- codegen/smithy-go-codegen/src/test/java/software/amazon/smithy/go/codegen/DocumentationConverterTest.java
This removes the indentation of lists, as indenting would only cause the line to be treated as a code block in godoc.
> Fix list formatting

- transport/http/client.go
- transport/http/request.go
Closes the SafeReadCloser after each request attempt.
> Call Close on SafeReadCloser after client.Do

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/EndpointHostPrefixMiddleware.java
- transport/http/middleware_metadata.go
- transport/http/request.go
Endpoint host prefix addition was being performed after a request was signed. This led to a incorrectly signed request. 
[x] This changes moves the endpoint mutation to a build step middleware, that will be performed before signing.  
[x] We also add a `DisableEndpointHostPrefix` and `IsEndpointHostPrefixDisabled` method on transport/http which provides an ability to turn host prefixing off. This would be useful when applying customizations or for testing purposes.
Related to https://github.com/aws/aws-sdk-go-v2/pull/862 and https://github.com/aws/aws-sdk-go-v2/pull/863
> moves host prefix addition to a build step middleware

- transport/http/middleware_content_length.go
- transport/http/middleware_content_length_test.go
fixes https://github.com/aws/aws-sdk-go-v2/issues/915
* unsets a request stream if the stream is empty.  
> update content length middleware to unset stream if stream is empty

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoValueAccessUtils.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/Paginators.java
- codegen/smithy-go-codegen/src/main/resources/META-INF/services/software.amazon.smithy.go.codegen.integration.GoIntegration
Depends on https://github.com/awslabs/smithy/pull/628
> PaginationTrait Support

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/Waiters.java
Error type symbol did not include service namespace which resulted in a incorrect namespace. This pr fixes the issue.
> waiter: fixes error type import namespace

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoDelegator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/UnionGenerator.java
* Adds additional package documentation to indicate that types that satisfy union interface types.
* Adds an example for package documentation that indicates how a union can be used when received in output responses.
Weather example: https://gist.github.com/skmcgrail/fcea7b51cb2bd8da6f4e28db64ae6fe1
> Generate Union Documentation and Output Usage Example

- logging/logger_test.go
> logging: cleanup Noop vs Nop naming

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoWriter.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/OperationGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ShapeValueGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/UnionGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolTestGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolUnitTestGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/knowledge/GoUsageIndex.java
Normalizes map keys for shapes targeted by httpPrefixHeaders during deserialization. Also adds a comment when writing docs that are affected by this.
> Normalize map keys for shapes targeted by httpPrefixHeaders during deserialization 

- .github/workflows/api_diff_check.yml
- .travis.yml
- CONTRIBUTING.md
Updates TravisCI and GitHub Actions to refer to main branch.
> Update master to main

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
- middleware/ordered_group.go
Updates the middleware ordering behavior to preallocate its order item slices/maps to prevent future allocations.
Fixes #162
Example of v2 SDK's benchmark different
```go
benchmark                                          old ns/op     new ns/op     delta
BenchmarkCustomizations/small/smithy/default-4     98471         80525         -18.22%
BenchmarkCustomizations/small/smithy/default-4     127331        95931         -24.66%
BenchmarkCustomizations/small/smithy/default-4     143848        87465         -39.20%
BenchmarkCustomizations/small/smithy/default-4     250105        98629         -60.56%
BenchmarkCustomizations/small/smithy/default-4     190916        93149         -51.21%
BenchmarkCustomizations/small/smithy/default-4     149556        86324         -42.28% …
```
>  middleware: Preallocate middleware ordering slices to reduce allocations

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ServiceGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ConfigField.java
Adds generating client functional option helpers to client packages. These make it a little bit more convenient to set Client options without creating the closure manually.
Client options must be opt-in to have the With helpers generated for them.
Fixes #143
V2 SDK api_client.go diff
```diff
+// WithAPIOptions returns a functional option for setting the Client's APIOptions
+// option.
+func WithAPIOptions(optFns ...func(*middleware.Stack) error) func(*Options) {
+       return func(o *Options) {
+               o.APIOptions = append(o.APIOptions, optFns...)
+       }
+}
```
A aws-sdk-go-v2 PR will need to be made to update the AWS SDK specific config fields that should include `With `helpers.
> codegen: Generate client option helpers

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
This removes the CLA provision from CONTRIBUTING.md and clarifies the license
in the pr template.
> Remove CLA and clarify license in pr template

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/EnumGenerator.java
Fixes the generated enum value names to not be lower cased when capitalized.
Related to https://github.com/aws/aws-sdk-go-v2/issues/1013
> codegen: Fix enum value generated name to not be lowercased

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ServiceGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
- middleware/middleware.go
- middleware/stack_values.go
- middleware/stack_values_test.go
- transport/http/middleware_metadata.go
Adds utilities for values that are intended to be scoped to individual stacks. Provides utilities for bulk clearing these values as well.
Related to aws/aws-sdk-go-v2#914
---
* hostnameImmutableKey
* hostPrefixDisableKey
* Logger
>  middleware: Add utility for stack scoped stack values

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
Updates the codegen to use correct hash for smithy-go module.
> Update codegen to correct gohash

- encoding/xml/xml_decoder.go
- encoding/xml/xml_decoder_test.go
This the smithy-go half of what's needed to address aws/aws-sdk-go-v2#1013
This updates the XML decoder to un-resolve xml namspaces in
attributes. The Go decoder resolves them fully by default, but we
need the short names to match attributes to members while
decoding.
> Un-resolve xml attribute namespaces

- .travis.yml
Updates CI tests to build Go 1.15.x and tip, dropping Go 1.14.
> Update CI tests to use Go 1.15 +, drop 1.14

- time/time_test.go
Fixes #257 by updating the protocol test for time formatting to not overflow on 32bit systems.
> time: Fix test failing on 32bit architecture

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
- time/time.go
- time/time_test.go
Correct millisecond unix-time behavior to mimic the V1 AWS SDK for Go.
> Correct millisecond unix-time behavior to mimic V1.

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/AddOperationShapes.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenUtils.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SyntheticClone.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpRpcProtocolGenerator.java
- codegen/smithy-go-codegen/src/test/java/software/amazon/smithy/go/codegen/AddOperationShapesTest.java
Updates the SDK's generated serializers and deserializers to skip unmodeled
input and output shapes for operations.
This issue caused generated deserializers to attempt to deserialize
operation responses that were not modeled, resulting in an error.
Whereas the SDK should of ignored the response if one was present for
operations without a modeled output.
Related to https://github.com/aws/aws-sdk-go-v2/issues/1047
Fixes #262
Unmodeled Input shape serializer functions are not generated.
This update changes API protocol operation serializers for HTTP binding protocols to skip serialization of the request document if the operation's input was not modeled.
This change is **not** applied to HTTP RPC protocol serializations. This is due to the AwsQuery protocol requiring some protocol specific …
> codegen: Update generated serde to skip unmodeled input/outputs

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ServiceGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ConfigField.java
Updates Config field to support withHelper option it partially supports. The withHelper option is used to generate a With-Helper function for a Config Field.
> add support for withHelper for config field

- codegen/smithy-go-codegen-test/model/main.smithy
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/Waiters.java
update smithy waiters to walk shape and get correct target shape to be used to compare
> fix smithy-waiters to type cast compared members correctly.

- logging/logger.go
Adds `LoggerFunc` type to the logging package. Allows for easily satisfying the `Logger` interface by wrapping a function.
> Add LoggerFunc to logging package.

- transport/http/time.go
- transport/http/time_test.go
Co-authored-by: Daniel Hochman <danielhochman@users.noreply.github.com>
Fixes https://github.com/aws/aws-sdk-go-v2/issues/1115 by relaxing the standard library's `http.ParseTime`.
> Add ParseTime for HTTP Date Parsing

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoValueAccessUtils.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
Unboxed types for numbers and boolean values will be serialized regardless if they are the default value if they are marked with the required trait.
* Fixes an uncovered bug where URI parameters for numbers or boolean that were 0 or false would result in an invalid error. This condition is only applicable to prevent empty string values from being present in the URI.
> Serialize Unboxed Members marked as Required

- transport/http/time.go
- transport/http/time_test.go
Adds support for HTTP date formats that contain a shortened two-digit year.
Related: https://github.com/aws/aws-sdk-go-v2/issues/1131
> Add support for shortened year format in HTTP Date

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/Paginators.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/trait/PagingExtensionTrait.java
Support for extending paginators with custom runtime trait. Allows for specifying a more results key that should checked before the token.
Related: https://github.com/aws/aws-sdk-go-v2/issues/1140
> Support for extending paginators with custom runtime trait

- .github/workflows/api_diff_check.yml
- go.mod
- go.sum
Fixes the APIDiff GitHub action to correctly get the gorelease tooling.
Correct the smithy-go module's minimum Go version to 1.15 not 1.14. Also updates `go-cmp` to correct 0.5.4 version.
> Fix GitHub APIDiff action workflow to get gorelease tool correctly

- codegen/smithy-go-codegen-test/build.gradle.kts
Fixes the codegen artifact unit test for Go 1.16 to work with the go.sum file not being updated.
>  Fix codegen artifact unit test for Go 1.16

- .travis.yml
- CHANGELOG.md
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
Adds change notes for smithy-go v1.2.0 go module release, and codegen update.
```
* Fix support for parsing shortened year format in HTTP Date header.
* Fix GitHub APIDiff action workflow to get gorelease tool correctly.
* Fix codegen artifact unit test for Go 1.16
* Fix generating paginator nil parameter handling before usage.
* Fix Serialize unboxed members decorated as required.
* Add ability to define resolvers at both client construction and operation invocation.
* Support for extending paginators with custom runtime trait
```
> Add smithy-go's v1.2.0 release

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
- transport/http/url.go
- transport/http/url_test.go
Updates the Smithy SDK client httpbinding serializers to use the JoinPath and JoinRawQuery utilities to ensure paths and query are joined correctly.
Related to # https://github.com/aws/aws-sdk-go-v2/issues/1191
> codegen: Update SDK clients to use utilities for joining URL Path and RawQuery

- transport/http/host.go
- transport/http/host_test.go
* customers can not specify ports with endpoints. 
* Update validateEndpointHost function to allow valid port usage. 
* Adds test.
Fixes https://github.com/aws/aws-sdk-go-v2/issues/1035
> transport/http : Loosen hostname validation to allow ports to be specified

- io/ringbuffer.go
- io/ringbuffer_test.go
Fixes an index out of bounds in the RingBuffer implementation.
Fixes https://github.com/aws/aws-sdk-go-v2/issues/1200
> Fix RingBuffer panic due to out of bounds index

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
Update smithy-go version to point to release v1.3.1. 
PR should be merged before #284 is merged.
> Update smithy-go version to point to release v1.3.1

- encoding/xml/encoder_test.go
- encoding/xml/escape.go
- local-mod-replace.sh
Adds escaping rules for `next line` (U+0085) and `line separator` (U+2028) to XML encoder.
> Escape Next Line and Line Start in XML Encoder

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenVisitor.java
Updates smithy-go codegen to clone operation top level input and output to be performed before other integrations can preprocess models. This ensures that the preprocessors are working on the correct operation top level shapes.
> Create operation input/output synthetic shapes before integrations preprocess model

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/AddOperationShapes.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenUtils.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoCodegenPlugin.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/OperationGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/StructureGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/DocumentShapeDeserVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/DocumentShapeSerVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolGeneratorUtils.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolUnitTestGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpRpcProtocolGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ProtocolGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/Waiters.java
- codegen/smithy-go-codegen/src/test/java/software/amazon/smithy/go/codegen/AddOperationShapesTest.java
- encoding/httpbinding/encode.go
- encoding/httpbinding/encode_test.go
Description of changes:
*  Adds support for renaming conflicting shapes within service closure
*  Adds support for httpQueryParams location
> Migrate to Smithy 1.7.0

- CHANGELOG.md
Updates changelog in preparation for smithy-go v1.4.0 release.
> Update changlog in prep for v1.4.0 release

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
Updates smithy-go's codegen to use version v1.4.0 of smithy-go Go modules.
> Update smithy-go codegen version to v1.4.0

- codegen/build.gradle.kts
This updates the java group id to be namespaced to the language. This
will be necessary for eventually publishing the generators.
> Update java group id

- .github/workflows/codegen.yml
- .github/workflows/go.yml
- .travis.yml
Updates the SDK's CI to use GitHub actions intead of Travis for most CI tasks. Travis is still used for Go tip.
> Add GitHub actions instead of Travis for Go CI tests

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolGeneratorUtils.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpRpcProtocolGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ProtocolGenerator.java
Support the delegation of determining the errors that can occur for an operation. Required to implement support for [awsQueryError](https://awslabs.github.io/smithy/1.0/spec/aws/aws-query-protocol.html#aws-protocols-awsqueryerror-trait) trait.
> Support the delegation of determining the errors that can occur for an operation

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ShapeValueGenerator.java
This updates the protocol test generator to properly handle generating non-numeric float values. It doesn't actually update any of the protocol support.
See: https://github.com/awslabs/smithy/pull/828
> Generate non-numeric floats in protocol tests

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/OperationGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ServiceGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ClientMember.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ClientMemberResolver.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/GoIntegration.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/RuntimeClientPlugin.java
```
type Client struct {
options Options
\\ client members added via runtime plugins
cache map[string]string
}
```
> Adds support for integrating client members via plugins

- codegen/smithy-go-codegen/build.gradle.kts
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/DocumentationConverter.java
This updates to avoid the term whitelist in the code base. ~~jsoup has a `Whitelist` class that we need to use, unfortunately, so that is the remaining usage. This is being deprecated in jsoup 1.14 but that [hasn't been released yet](https://github.com/jhy/jsoup/issues/1481).~~ Update: they released! PR updated
> Remove use of the term whitelist

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolUnitTestGenerator.java
- encoding/httpbinding/encode.go
- encoding/httpbinding/header.go
- encoding/httpbinding/query.go
- encoding/httpbinding/uri.go
Adds support for Smithy 1.9 which introduces support for `NaN`, `Infinity`, and `-Infinity`.
> Smithy 1.9 Support

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/OperationGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/StructureGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ProtocolGenerator.java
`AwsQueryError` trait overrides the error code for an error type. 
https://awslabs.github.io/smithy/1.0/spec/aws/aws-query-protocol.html#aws-protocols-awsqueryerror-trait
This change allows us to override errorCode for a protocol generator, defaulting to error shape name as error code.
> add support for go-integrations overriding error code for error types

- middleware/metadata.go
- middleware/metadata_test.go
Adds a new Clone method to the middleware Metadata type. This provides a shallow clone of the entries in the Metadata.
Used by https://github.com/aws/aws-sdk-go-v2/pull/1345 to clone attempt result metadata
> middleware: Add Clone to Metadata

- .github/workflows/api_diff_check.yml
- .github/workflows/codegen.yml
- .github/workflows/go.yml
- document/json/shared_test.go
- ptr/gen_scalars.go
- ptr/generate.go
* Updates smithy-go's `build` tags to use go 1.17's formatting style of `// go:build ...`.
* Updates CI for Go 1.17.
> Updates smithy-go for Go 1.17

- Makefile
Updates smithy-go to use the same changelog and release tooling as AWS SDK for Go v2's.
> Update smithy-go to use SDK's changelog and release tools

- Makefile
Fix typo introduced into makefile breaking the `smithy-publish-local` command.
> fixup makefile smithy-publish-local rule typo

- Makefile
Adds a make task to the `smithy-go` repository that will call the repotool's `moduleverison` utility. This will return the current version of the `smithy-go` Go module. Allows release automation to call `make release` followed by `make module-version` to get the current Go module version without using complicated checking for Go module changes
> Add make task to get smithy-go module version

- codegen/config/spotbugs/filter.xml
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/EventStreamGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoEventStreamIndex.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/OperationGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ServiceGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/StructureGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/UnionGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ConfigFieldResolver.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/DocumentShapeDeserVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/DocumentShapeSerVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolGeneratorUtils.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolUtils.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpRpcProtocolGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ProtocolGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ProtocolUtils.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ValidationGenerator.java
- internal/uuid/uuid.go
- rand/uuid.go
- rand/uuid_test.go
- sync/error.go
- transport/http/middleware_close_response_body.go
- transport/http/middleware_http_logging.go
- transport/http/middleware_min_proto.go
- transport/http/request.go
Adds support for event streaming in protocol implementations. Provides the basic type and interface generator for operations, and delegates the concrete implementations to the underlying protocols.
Fixes https://github.com/aws/aws-sdk-go-v2/issues/1317
> Add support for event streaming in protocols

- codegen/smithy-go-codegen-test/build.gradle.kts
- codegen/smithy-go-codegen/build.gradle.kts
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolUnitTestGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolUnitTestRequestGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolUnitTestResponseGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpRpcProtocolGenerator.java
Updates the smithy-go code generation to 1.14.0 and makes several modifications to properly support for new AWS protocol test requirements.
> Upgrade to Smithy 1.14.0

- codegen/smithy-go-codegen-test/build.gradle.kts
Fixes the SDK's code generation to pin smithy-cli to $smithyVersion to restrict the supported version.
> Adds smithy-cli dependency to prevent auto use of smithy-cli 1.16

- .changelog/b8bab33defab491db0c1f257f2435d1e.json
- codegen/gradle.properties
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
- transport/http/headerlist.go
- transport/http/headerlist_test.go
Updates smithy-go to pin to the smithy 1.17.0 version.
Updates the code generation to handle (de)serialization of quoted header list values.
> Update smithy-go to pin updated version of smithy

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ServiceGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ConfigFieldResolver.java
Updates the API client code generation to optionally take the Client
value as input. Allowing finalizers to identify differences between what
the client was originally configured with and the operation's new
options.
> codegen: Add support for operation finalize option take client

- transport/http/checksum_middleware.go
- transport/http/checksum_middleware_test.go
- transport/http/request.go
- transport/http/request_test.go
Adds a fix for the HTTP Request setStream to correctly handle empty
and empty unseekable teams. This fixes a bug where the HTTP request
would attempt to rewind an empty unseekable stream due to assumptions
that the stream would be nil if content length is 0.
Related to #356
> transport/http: Add fix for HTTP request stream not seekable

- encoding/httpbinding/uri.go
This fixes a dropped `err` variable in `encoding/httpbinding`.
> encoding/httpbinding: fix dropped error

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpRpcProtocolGenerator.java
> Fix duplicate Content-Type for RPC based Event Streams

- .changelog/b40d60c0b28c445695ae7cd1fdd96596.json
- go.mod
- go.sum
Updates smithy-go unit testing dependency go-cmp to v0.5.8
> Update go-cmp dependency from v0.5.7 to 0v.5.8

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolVisitor.java
n/a
Updates the SDK's code generation of modeled API error members to escape ErrorMessage since its a reserved word and used as a generated method.
Any API model that already had an API error shaped modeled with an `ErrorMessage` member would of failed to compile due to the method generated on the struct with the same name.
> codegen: Update codegen to escape ErrorMessage API error member

- .changelog/461d165a25e346669f076407175b6bd5.json
- encoding/json/escape_test.go
- encoding/json/object.go
- encoding/json/object_test.go
https://github.com/aws/aws-sdk-go-v2/issues/1764
- fixed escaping on `writeKey` function. 
- Added test coverage for that
- Fixed typo
- Added test coverage for `escapeStringBytes`
> Dynamo putitem escaping

- codegen/gradle.properties
- codegen/smithy-go-codegen-test/build.gradle.kts
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoValueAccessUtils.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoWriter.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ShapeValueGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/knowledge/GoPointableIndex.java
N/A
---
Upgrade to Smithy IDL 2.0:
- Upgrade `smithyVersion` to 1.23.1
- Extract Smithy Gradle Plugin to `smithyGradleVersion` to 0.6.0
- Add partial support `ENUM` support to maintain consistent code generation
- Omit deprecation comments for Prelude shapes
**These changes are a temporary workaround.**
In the future, smithy-go should be refactored to use a visitor pattern instead of switch-statements on `ShapeType` / if-statements on `EnumTrait`.
---
*Testing:*
File Structure:
```tree
.
├── aws-sdk-go-v2
└── smithy-go
```
1. smithy-go: Ran `make smithy-clean smithy-build smithy-publish-local smithy-clean`.
2. aws-sdk-go-v2: Ran `make`
3. aws-sdk-go-v2: Verified expected diffs in protocol tests and services
---
<p …
> Upgrade to Smithy IDL 2.0

- .changelog/07aa0cb9fd244f52aac3f66f0047b25e.json
- auth/bearer/docs.go
- auth/bearer/middleware.go
- auth/bearer/middleware_test.go
- auth/bearer/token.go
- auth/bearer/token_cache.go
- auth/bearer/token_cache_test.go
- codegen/smithy-go-codegen-test/model/main.smithy
- codegen/smithy-go-codegen-test/smithy-build.json
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/auth/HttpBearerAuth.java
- codegen/smithy-go-codegen/src/main/resources/META-INF/services/software.amazon.smithy.go.codegen.integration.GoIntegration
- context/suppress_expired.go
- internal/sync/singleflight/LICENSE
- internal/sync/singleflight/docs.go
- internal/sync/singleflight/singleflight.go
- internal/sync/singleflight/singleflight_test.go
- transport/http/request.go
Adds support for the [Smithy httpBearerAuth](https://awslabs.github.io/smithy/1.0/spec/core/auth-traits.html#httpbearerauth-trait) authentication trait to smithy-go. This allows the SDK to support the bearer authentication flow for API operations decorated with `httpBearerAuth`. An API client will need to be provided with its own `bearer.TokenProvider` implementation or use the `bearer.StaticTokenProvider` implementation.
> Add support for Smithy httpBearerAuth authentication trait

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoDelegator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoWriter.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoWriterDelegator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ImportDeclarations.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ManifestWriter.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/testutils/ExecuteCommand.java
- codegen/smithy-go-codegen/src/test/java/software/amazon/smithy/go/codegen/GenerateStandaloneGoModuleTest.java
- codegen/smithy-go-codegen/src/test/java/software/amazon/smithy/go/codegen/TestUtils.java
Updates the smithy-go codegen to include support for writing file manifests for non-model based Go code generation. This allows code generation for standalone Go modules that are not smithy model based. Including Go module unit tests.
Adds GoWritable for lazy code writing. Allows a Writable to be returned from a method improving the ability to do inline code generation.
> codegen: Updates codegen to support non-model writing, and lazy writable

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoWriter.java
- codegen/smithy-go-codegen/src/test/java/software/amazon/smithy/go/codegen/GenerateStandaloneGoModuleTest.java
Refactors the GoWriter `goBlockTemplate` and `writeGoBlockTemplate` methods map of argument parameters to be easier to work with and not require inline arrays to be defined by the caller.
> codegen: Refactor goBlockTemplate args to be easier to work with

- codegen/smithy-go-codegen/src/main/resources/software/amazon/smithy/go/codegen/smithy-tests/mixin-test/expected/changeCardInput.go.mixin
- codegen/smithy-go-codegen/src/main/resources/software/amazon/smithy/go/codegen/smithy-tests/mixin-test/expected/changeCardOutput.go.mixin
- codegen/smithy-go-codegen/src/main/resources/software/amazon/smithy/go/codegen/smithy-tests/mixin-test/mixin-test.smithy
- codegen/smithy-go-codegen/src/test/java/software/amazon/smithy/go/codegen/MixinCodegenTest.java
N/A
---
Add unit test for mixin code generation.
---
*Testing*
Ran `make smithy-clean smithy-build smithy-publish-local smithy-clean`.
---
> Add unit test for mixin code generation

- codegen/go.mod
- modman.toml
n/a
Breaks out the smithy codegen directory into a Go module so it can be ignored by Go's module packaging system. In addition, so that go commands are not run on any go mixin or test files used by codegen.
---
Before this can be merged in, we need to investigate the impact on the release automation determining what is the the latest smithy-go module version.
> codegen: Breakout codegen directory into its a Go module

- transport/fields.go
- transport/fields_test.go
- transport/fieldset.go
- transport/internal/fieldset/main.go
Adds an accessor method to FieldSet, GetHeaderFields. This method returns copy of the slice of Field stored within the FieldSet.
Makes Fields type unexported since it doesn't need to be exposed.
> transport: Add accessor method to get slice of Fields

- codegen/gradle.properties
- codegen/smithy-go-codegen-test/build.gradle.kts
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/Paginators.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/knowledge/GoPointableIndex.java
N/A
---
**Note: This change introduces break/fix's for pointable types.**
Update paginators code generation
- Use the member shape to check pointability instead of the target shape for passing the limit from the options to the params.
Fix GoPointableIndex bugs
- `isMemberDereferencable()` previously used the `isShapeDereferencable()` method, but now is switched to check the that it is NOT in the `INHERENTLY_NONDEREFERENCABLE` set.
- `isMemberPointable()` used to incorrectly categorize pointability due to an incorrect condition using `NullableIndex::isNullable()` method, but is now using a new conditionals and the updated `NullableIndex::isMemberNullable()` method with the `CLIENT_ZERO_VALUE_V1_NO_INPUT` check mode.
Chores:
- Add …
> Upgrade to smithy 1.25.0

- .changelog/52ea7af068da449f918698755a7d0f01.json
- document/json/encoder.go
- document/json/encoder_test.go
This resolves github issue 391 where encoding of document types is not checking to see if nested types are explicitly marked for no serialization or deserialization. In order to to check for every layer of nesting, I moved the noserde check to the recursive layer from the original top-level function. This mimics how it correctly works in decoding
> [issues-391] Fix document typecheck in encoding  for nested types

- Makefile
> Add makefile commands for unit testing

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenUtils.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/IntEnumGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ShapeValueGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
- codegen/smithy-go-codegen/src/main/resources/software/amazon/smithy/go/codegen/smithy-tests/int-enum-shape-test/expected/types/enums.go
N/A
---
Due to type definitions requiring strict casting and implementation
overhead in protocol generation, this commit uses type aliases to
generate intEnums as an intermediate step until migrating back to
type definitions.
This change is backwards compatible except for the removed `Values()`
method that was on intEnum type definitions, but not definable on type
aliases since defining methods on base types (`int32`) is not permitted.
Note: No AWS services use the intEnum shape YET, so for aws-sdk-go-v2, it is backwards compatible.
---
*Testing:*
Temporarily change all repo smithy versions to 1.28.0 (not published at the time of the PR).
1. smithy: `./gradlew clean build check publishToMavenLocal` using this PR: …
> Update intEnum generation to use type alias

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/StructureGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolGeneratorUtils.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpRpcProtocolGenerator.java
Makes changes to AwsJson protocol generator.
* Introduces `ErrorCodeOverride` field to error structs
* Returns `ErrorCodeOverride` if not empty. Else returns default error code
* Introduces `generateErrorShape` method to allow override default error block for unmodeled errors
For example, AWS code bases would have something like the following to override `generateErrorShape`:
```java
@Override
protected Set<StructureShape> generateErrorShapes(
GenerationContext context, OperationShape operation, Symbol responseType) {
if (isAwsQueryCompatibleTraitFound(context)) {
return HttpProtocolGeneratorUtils.generateErrorDispatcher(
context, operation, responseType, this::writeErrorMessageCodeDeserializer,
this::getOperationErrors, (writer) -> …
```
> Add `ErrorCodeOverride` to error structs

- codegen/smithy-go-codegen/src/test/java/software/amazon/smithy/go/codegen/GenerateStandaloneGoModuleTest.java
This unit test doesnt seem to play nice when run within a directory with a `go.work` file. This fixes that based on the suggestion described in the issue below
Fixes https://github.com/aws/smithy-go/issues/392
> Fix generate standalone go module unit test

- .github/CODEOWNERS
N/A
Add @aws/smithy to CODEOWNERS
> Add @aws/smithy to CODEOWNERS

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoModGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoModuleInfo.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoSettings.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ManifestWriter.java
- codegen/smithy-go-codegen/src/test/java/software/amazon/smithy/go/codegen/GenerateStandaloneGoModuleTest.java
Related to changes in #405
---
Currently, `ManifestWriter` and `GoModGenerator` use different
ways to calculate non-standard library dependencies and
the go directive (minimum go version), which could produce
inconsistencies.
This commit updates both writers to use the same source of
information (`GoModuleInfo`) for writing `generated.json`
and `go.mod`.
---
*Testing:*
All tests were done in `smithy-go-codegen-test`:
Test Case| `goDirective` in `smithy-build.json` | `goDirective` in `generated.json` | `goDirective` in `go.mod`
---|---|---|---
`goDirective < default` | `1.12` | `IllegalArgumentException` | `IllegalArgumentException`
`goDirective == default` | `1.15` | `1.15` | `1.15`
`goDirective > default` | `1.18` | `1.18` | `1.18` …
> Use GoModuleInfo for both ManifestWriter and GoModGenerator

- .changelog/935d5acf9da941a2b1b8b326494e5c33.json
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/StructureGenerator.java
> prevent nil pointer deref in ErrorCode() method of generated structs

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/Synthetic.java
N/A.
When using smithy diff or trait comparisons for the Go `Synthetic`
trait, the following exception is thrown in the `createNode()`
implementation:
```text
"attempted to serialize runtime only trait"
```
This is due to inheriting from `AbstractTrait`'s equality methods which
use the `ToNode()` method which calls the `createNode()` method.
This change adds an `equals()` and `hashCode()` implementation for the
Go `Synthetic` trait that does not use `ToNode()` or `createNode()`.
`ToNode()` cannot be overriden since `AbstractTrait`'s implementation is
marked as `final`.
*Testing:*
1. Running `make smithy-clean smithy-build smithy-publish-local smithy-clean` succeeded.
2. Running `make generate` in aws/aws-sdk-go-v2 produced no diffs.
By …
> Add Go Synthetic Trait equality methods

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ServiceGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ConfigField.java
- middleware/metadata.go
This utility may be necessary for consumers if they want to deprecated a With helper function that corresponds to a config field
> Add deprecated option to config field resolvers

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/endpoints/EndpointMiddlewareGenerator.java
These names need to be used by other middlewares. So they cannot be private
> Make middleware name getters public

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/endpoints/EndpointMiddlewareGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/EndpointHostPrefixMiddleware.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/GoIntegration.java
Instead of using a model filter to completely remove the endpoint host prefix middleware from every operation. Adding a runtime disabler allows for custom v1 resolvers to still use the endpoint host prefix middleware.
> Disable Host Prefix in certain case

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/endpoints/EndpointClientPluginsGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/endpoints/EndpointMiddlewareGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/endpoints/EndpointResolutionGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/endpoints/EndpointTestsGenerator.java
1. only generate middleware if ruleset exists (can be changed later)
2. wrap string values for static context params in quotes
3. fix net url import with symbols
> Fix various bugs failing make unit

- .github/workflows/codegen.yml
All EP20 refs in GH workflows should have been removed in the Github workflows.
> Remove EP20 references

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/endpoints/EndpointResolverGenerator.java
Prevents generation of unreachable code by not considering the static `uriEncode` function as a condition when deciding whether to generate fallback.
A source comment next to the change contains a more detailed explanation.
> fix: properly prevent unreachable error codegen in endpoint rules

- codegen/smithy-go-codegen/build.gradle.kts
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/CodegenVisitor.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoUniverseTypes.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/OperationGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/auth/AuthGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/auth/AuthParameter.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/auth/AuthParametersGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/auth/AuthParametersResolver.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/auth/AuthParametersResolverGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ProtocolGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/RuntimeClientPlugin.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/SigV4AuthParameters.java
- codegen/smithy-go-codegen/src/main/resources/META-INF/services/software.amazon.smithy.go.codegen.integration.GoIntegration
* Add code generation for modeled auth resolver parameters.
* The only "universal" param is the operation name. This is resolved by implementing an `operationName()` interface on input structures.
* An additional "region" field is generated for sigv4x services.
* Add codegen for auth resolver param bindings.
* Add `GoIntegration` support for loading both auth params and resolvers.
> generate auth params and bindings

- .changelog/a33cd9f8b5d5438a8f8140ee4f39c2f7.json
- transport/http/middleware_header_comment.go
- transport/http/middleware_header_comment_test.go
Previously reviewed in https://github.com/aws/aws-sdk-go-v2/pull/2202.
> feat: add http.WithHeaderComment middleware

- auth/identity.go
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoStdlibTypes.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoWriter.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/OperationGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ServiceGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SetOperationInputContextMiddleware.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoTypes.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolUtils.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/auth/GetIdentityMiddlewareGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/auth/ResolveAuthSchemeMiddlewareGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/auth/SigV4aTrait.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/auth/SignRequestMiddlewareGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/endpoints/EndpointClientPluginsGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/endpoints/EndpointMiddlewareGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ConfigFieldResolver.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/EndpointHostPrefixMiddleware.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/auth/SigV4aDefinition.java
* Add sigv4a auth definition
* There's a temporary sigv4a "trait" which is used downstream, to be replaced by the real thing at the time it's added
* Reorder operation phasing: auth resolution, identity retrieval, endpoint resolution, and signing now occur in that order at the beginning of the finalize phase
* The operation input is now stored on the context at the beginning of serialize to be accessed as necessary by later phases
* "resolve endpoint" middleware is now always generated and simply empty without a ruleset. A large number of components index off of it (both here and in the SDK downstream), better to have it be an "explicit" phase to not have to worry about it being there for stack operations
* Path merging behavior now occurs as part of endpoint resolution, since that …
> feat: sra i&a: add sigv4a and reorder operation phases

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/endpoints/AuthSchemePropertyGenerator.java
Endpoint resolution spec explicitly says we're not supposed to error on unrecognized signer names, this is a minor regression from the merge of #469. This change restores the intended behavior.
> pass through unrecognized signer names as-is

- auth/option_test.go
- properties_test.go
- transport/http/properties_test.go
These tests are needed to increase test coverage
> Add unit tests to increase test coverage

- .changelog/966e9ee62f384f2aa660c8bac175addb.json
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoWriter.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ServiceGenerator.java
- endpoints/private/rulesfn/strings.go
Generates a getter for `Options` on service clients, which returns a copy of client config.
> codegen: add Options() method to read copied client config

- transport/http/auth_schemes_test.go
- transport/http/identity_test.go
> Add more unit tests to increase test coverage

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/requestcompression/RequestCompression.java
We MUST iterate over operations with `TopDownIndex.getContainedOperations` rather than `ServiceShape.getAllOperations`, the latter only covers operations listed in the service shape's `operations` list and will miss anything that's listed as part of a `resource` on the service.
We missed this in the original implementation with the protocol tests because the operations that use the compression trait there are actually in the `operations` list of the service shape.
> fix: request compression codegen for resource operations

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoStdlibTypes.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoWriter.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoTypes.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolUtils.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/service/Util.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/service/protocol/JsonDeserializerGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/service/protocol/JsonSerializerGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/service/protocol/aws/AwsJson10ProtocolGenerator.java
Implements partial serde. Shape support isn't exhaustive but for PoC purposes has been verified to generate deserializers for every SQS request shape.
> feat-svcgen-deserialize

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/auth/AuthParametersResolverGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/auth/ResolveAuthSchemeMiddlewareGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/endpoints/EndpointMiddlewareGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/endpoints/EndpointParameterBindingsGenerator.java
During the ep2.0 resolution, the accountID param is retrieved from ctx's credentials, thus in this PR, the ctx is added as a new param into endpoint binding func codegen.
> Add accountID into endpoint2.0 param binding

- .changelog/5974e1d2ba434e1fba73f9632f9b1063.json
- .github/workflows/api_diff_check.yml
- .github/workflows/codegen.yml
- .github/workflows/go.yml
- auth/bearer/middleware_test.go
- auth/bearer/token_cache_test.go
- document/json/decoder_test.go
- document/json/encoder_test.go
- document/json/shared_test.go
- encoding/xml/xml_decoder_test.go
- endpoints/private/rulesfn/uri_test.go
- go.mod
- io/ringbuffer_test.go
- middleware/ordered_group_test.go
- middleware/stack_test.go
- testing/xml/sort_test.go
- transport/http/headerlist_test.go
- transport/http/middleware_headers_test.go
- transport/http/middleware_http_logging_test.go
With the release of go 1.22, we're bumping our minimum versions to 1.20.
This patch also removes most of the use of the `go-cmp` external dependency. We can't remove it completely yet because the assertion utility that generated event tests use downstream depends on it. That will have to be re-evaluated/untangled in a future patch.
> chore: bump min go to 1.20 and remove 95% of the go-cmp dependency

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoWriter.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/Waiters.java
Adds a field to pass API client options through to calls made by waiters:
```go
+       // Functional options to be passed to all operations invoked by this client.
+       //
+       // Function values that modify the inner APIOptions are applied after the waiter
+       // config's own APIOptions modifiers.
+       ClientOptions []func(*Options)
+
```
> feat: add client config passthrough to waiter opts

- .changelog/5faed85326334a93a9b0a96284389287.json
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolUnitTestGenerator.java
- go.mod
- go.sum
- modman.toml
- testing/document.go
- testing/struct.go
- testing/struct_test.go
Removes the final thread of the runtime go-cmp dependency, refactoring `testing.CompareValues` to not use it.
Downstream protocol tests are passing, and standalone coverage has been added to test the new compare routine as well.
> remove go-cmp dependency

- codegen/build.gradle.kts
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/DocumentationConverter.java
- codegen/smithy-go-codegen/src/main/resources/software/amazon/smithy/go/codegen/smithy-tests/enum-shape-test/expected/types/enums.go
- codegen/smithy-go-codegen/src/main/resources/software/amazon/smithy/go/codegen/smithy-tests/int-enum-shape-test/expected/types/enums.go
- codegen/smithy-go-codegen/src/test/java/software/amazon/smithy/go/codegen/DocumentationConverterTest.java
fixes aws/aws-sdk-go-v2#2597
Improvements:
- Use Go doc links introduced in Go 1.19
- Separate paragraphs so they are rendered as separate blocks of text
> fix: improve Go doc formatter

- codegen/gradle.properties
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SymbolUtils.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/endpoints/EndpointClientPluginsGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/endpoints/EndpointParametersGenerator.java
Upgrade to smithy 1.49 to pull in fixed ec2query protocol tests: https://github.com/aws/aws-sdk-go-v2/issues/2627
Includes some minor code shuffle/deduping in response to having to check for the new (currently unused) `STRING_ARRAY` endpoint parameter type.
> upgrade to smithy 1.49

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/RuntimeClientPlugin.java
Add `GoIntegration` hook to override deserialization by shape.
The scaffolding for this was done with intent to expand to document (response body) deserialization should it ever be necessary but for now was only implemented to be recognized for HTTP bindings.
> add shape deserializer overrides

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
Related to aws-sdk-go-v2#2321
Add sync/atomic definition, so it can be used on clock skew detection
> add 'sync/atomic' to the list of Go dependecies

- .changelog/df65633a5ad44d44824adf6b784199e7.json
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/auth/AuthParametersResolverGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/auth/ResolveAuthSchemeMiddlewareGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/endpoints/EndpointMiddlewareGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/endpoints/EndpointParameterBindingsGenerator.java
Add context into endpoint param binding inputs codegen for aws accountid extraction from ctx identity
> Add context into endpoint param binding inputs

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/Paginators.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/Waiters.java
- codegen/smithy-go-codegen/src/main/resources/META-INF/services/software.amazon.smithy.go.codegen.integration.GoIntegration
This extensibility is required for user-agent tracking downstream.
Long-term these shouldn't be integrations, tracking fixing that in #517.
> add client opts extension point for waiters/paginators

- encoding/cbor/coerce_test.go
For "uint oob" tests in TestAsInt32 and TestAsFloat64 in encoding/cbor/coerce_test.go, cast the number to Uint in the error message just as the number is cast in the test itself, so as to avoid overflows when tested on 32-bit architectures.
Fixes `cannot use maxv + 1 (untyped int constant 2147483648) as int value in argument to fmt.Sprintf (overflows)` in TestAsInt32 and `cannot use maxv + 1 (untyped int constant 18014398509481985) as int value in argument to fmt.Sprintf (overflows)` in TestAsFloat64 on 32-bit platforms.
Detected by Debian CI running on 386; see https://ci.debian.net/packages/g/golang-github-aws-smithy-go/testing/i386/47149094/#L1260
> Cast numbers in "uint oob" test error messages to avoid overflows

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoJmespathExpressionGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/endpoints/EndpointParameterOperationBindingsGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/Waiters.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/Waiters2.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/util/ShapeUtil.java
- codegen/smithy-go-codegen/src/test/java/software/amazon/smithy/go/codegen/GoJmespathExpressionGeneratorTest.java
* Builds out support for additional jmespath expressions required by AWS SDK v2.
* The traversal pattern was beefed up in general - a `Variable` is now the input and output of a traversed expression, as well as the result of each intermediate phase.
* Consumes jmespath codegen in waiters integration.
**This implementation was verified by re-generating the public SDKs and ensuring that they compiled.**
~~This PR should not be merged as-is. It was submitted in this state such that the diff for the waiters integration was most easily read. We intend to do a trial rollout of the new waiter implementation downstream for the EC2 service. Before merging this PR we must do the following:~~
Closes #238
> [READY FOR MERGE] - implement full jmespath support in codegen for downstream AWS SDK v2

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/protocol/aws/AwsJson10ProtocolGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/protocol/aws/SerializeMiddleware.java
* Update Protocol Generator request serializer generation to a cleaner and complete build.
* Add a new class SerializeMiddleware that handles all generation for request serializers.
* Add support for shared serializers to handle complex input shapes, nested within serializer request generaiton.
> Add serializers middleware logic for protocol generator awsjson10.

- .github/workflows/api_diff_check.yml
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/protocol/aws/AwsJson10ProtocolGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/protocol/aws/DeserializeMiddleware.java
Protocol Generator: 
- generateSharedDeserializers contains revisions that attain all error shapes and generate shared deserializers with regular member shapes 
- generateSharedDeserializes generates deserializers specific to each operation and additional error info functions
- generateOperationErrorDeserializers handles all parts of error generation, including cycling through the different operations. There are 4 additional helper functions in protocol generator utilized here. 
Deserialize Middleware:
- Response Checks function calls the error deserializers if a non 200 error is reported
> Add awsJson10 Error Deserialization support.

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoWriter.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ServiceGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/SmithyGoDependency.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/auth/GetIdentityMiddlewareGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/auth/SignRequestMiddlewareGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/endpoints/EndpointMiddlewareGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpRpcProtocolGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/ObservabilityOptions.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/OperationMetricsStruct.java
- metrics/metrics.go
- metrics/nop.go
- metrics/smithy-otel-metrics/async.go
- metrics/smithy-otel-metrics/attribute.go
- metrics/smithy-otel-metrics/doc.go
- metrics/smithy-otel-metrics/float64.go
- metrics/smithy-otel-metrics/go.mod
- metrics/smithy-otel-metrics/go.sum
- metrics/smithy-otel-metrics/int64.go
- metrics/smithy-otel-metrics/metrics.go
- metrics/smithy-otel-metrics/option.go
- middleware/context.go
- tracing/smithy-otel-tracing/adapt.go
- tracing/smithy-otel-tracing/adapt_test.go
- tracing/smithy-otel-tracing/attribute.go
- tracing/smithy-otel-tracing/attribute_test.go
Metrics component of #470 (and downstream https://github.com/aws/aws-sdk-go-v2/issues/1744).
* adds metrics APIs
* adds `smithy-otel-metrics` library which binds a concrete OTEL SDK meter provider to the Smithy version of the API
* adds the following operation metrics as histograms - the units are in seconds per the OTEL spec. all by default have dimensions of (service, method), additional dimensions listed in parentheses where applicable
* `client.call.duration` - entire elapsed time of call from start to finish
* `client.call.serialization_duration` - time elapsed to serialize request, including any http bindings
* `client.call.deserialization_duration`- time elapsed to deserialize request, including http bindings and error deserialization
* `client.call.resolve_identity_duration` - …
> add metrics APIs and corresponding otel adapter

- aws-http-auth/credentials/credentials.go
- aws-http-auth/go.mod
- aws-http-auth/internal/v4/signer.go
- aws-http-auth/internal/v4/signer_test.go
- aws-http-auth/internal/v4/strings.go
- aws-http-auth/sigv4/e2e_test.go
- aws-http-auth/sigv4/sigv4.go
- aws-http-auth/sigv4/sigv4_test.go
- aws-http-auth/sigv4a/credentials.go
- aws-http-auth/sigv4a/e2e_test.go
- aws-http-auth/sigv4a/sigv4a.go
- aws-http-auth/sigv4a/sigv4a_test.go
- aws-http-auth/v4/v4.go
Closes #473
Closes #474 
Closes https://github.com/aws/aws-sdk-go-v2/issues/2634
> introduce new aws-http-auth module which implements sigv4 and sigv4a

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/testutils/ExecuteCommand.java
We had an issue where we had a hard time figuring out what the error was when running a test. Test was failing with
```
> Task :smithy-go-codegen:test
GenerateStandaloneGoModuleTest > testGenerateGoModule() FAILED
java.lang.Exception at GenerateStandaloneGoModuleTest.java:93
75 tests completed, 1 failed
> Task :smithy-go-codegen:test FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':smithy-go-codegen:test'.
> There were failing tests. See the report at: file://place/smithy-go/codegen/smithy-go-codegen/build/reports/tests/test/index.html
```
and the test report had just
```
java.lang.Exception: Command existed with non-zero code, [go1.20.14, test, -v, ./...], status code: 1
```
Since the logger …
> Print output when executing commands when exit code != 0

- .changelog/240018a27d404933a6038db3cf0aa991.json
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ServiceGenerator.java
- transport/http/client.go
- transport/http/metrics.go
- transport/http/metrics_test.go
Final list of metrics:
| Metric Name | Unit | Type | Description | Attributes (Dimensions) |
|-------------|------|------|-------------|-------------------------|
| client.http.connections.acquire_duration | s | Histogram | The time it takes a request to acquire a connection |
| client.http.connections.dns_lookup_duration | s | Histogram | The time it takes to do DNS lookup |
| client.http.connections.tls_handshake_duration | s | Histogram | The time it takes to perform a TLS handshake |
| client.http.connections.usage | {connection} | UpDownCounter | State of the connection pool | state: idle/acquired*** |
| client.http.do_request_duration | s | Histogram | Total time spent in Do() |
| client.http.time_to_first_byte | s | Histogram | Time from Do() to first response byte received |
*** …
> add http client metrics

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java
Had an issue where calling S3 with metadata with an empty value caused SDKs to not serialize the value and not send the header. This change allows prefix headers to have an empty value.
Remove restriction of not serializing empty values for prefix headers
> fix: allow empty headers on prefix headers

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/util/ShapeUtil.java
- codegen/smithy-go-codegen/src/test/java/software/amazon/smithy/go/codegen/GoJmespathExpressionGeneratorTest.java
While investigating an internal JMESPath expression, I noticed that it failed chaining a select at the end. After discussing it with @lucix-aws offline, this is because we had the wrong synthetic shape instead of the base one in Smithy.
Added a tests that covers this as well
> Update string shape from synthetic to base

- codegen/gradle.properties
Update to latest release of Smithy https://github.com/smithy-lang/smithy/releases/tag/1.52.1
This allows us to remove some `ignore` we set on the Go SDK
> Update Smithy version to 1.52.1

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoJmespathExpressionGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/endpoints/EndpointParameterOperationBindingsGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/endpoints/EndpointResolverGenerator.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/util/ShapeUtil.java
- codegen/smithy-go-codegen/src/test/java/software/amazon/smithy/go/codegen/GoJmespathExpressionGeneratorTest.java
* fix up various codegen issues w/ jmespath multiselect around shape lookup and null typing
* remove the selective deref logic we previously had when mapping string array endpoint params in operation context param bindings - this is no longer necessary, since jmespath projection and multiselect implicitly filter nil, and string array params are `[]string`, the types will always align
* fix endpoint rules generator to not try to dereference string slices inside conditions
> fixup jmespath multiselect codegen

- .changelog/3efb0d073e5544c2a9b84abdab930700.json
- encoding/httpbinding/path_replace.go
- encoding/httpbinding/path_replace_test.go
fixes #552 
Old serialization code only indexes first occurrence of target element with left bracket (e.g. `{key`) without considering common prefix cases like `{key1111}` and `{key}`. this pr fixes that by directly searching index of the whole element with the format of `{element}` or `{element+}`
> Fix: URI path element replace issue due to elements name overlap

- codegen/smithy-go-codegen-test/smithy-build.json
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoModuleInfo.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoSettings.java
We have very old defaults currently. Update this to use our latest Go version (1.21) and add a module file, since
> The go directive sets the minimum version of Go required to use this module. Before Go 1.21, the directive was advisory only; now it is a mandatory requirement: Go toolchains refuse to use modules declaring newer Go versions.
[ref](https://go.dev/doc/modules/gomod-ref)
> Change defaults when generating a client via smithy CLI

- codegen/smithy-go-codegen-test/smithy-build.json
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoModuleInfo.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoSettings.java
This reverts commit 95ba31879b6b65f46a57f2ca510ce0ce6e860c9e.
This feature may interact in unexpected ways with existing SDK codegen, so while we figure it out we'll roll back these changes. They will be re-applied later.
> Revert "Change defaults when generating a client via smithy CLI (#558)"

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/Waiters.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/Waiters2.java
Needed for https://github.com/aws/aws-sdk-go-v2/issues/2937
From [waiter workflow](https://smithy.io/2.0/additional-specs/waiters.html#waiter-workflow) step 4:
> If none of the acceptors are matched and an error was encountered while calling the operation, then transition to the failure state and stop waiting.
Our implementation, for reasons probably lost to time, omits this step, causing waiters to spin longer than they should. This change adds that missing behavior.
> add missing waiter retry breakout on non-nil non-matched error

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoJmespathExpressionGenerator.java
- codegen/smithy-go-codegen/src/test/java/software/amazon/smithy/go/codegen/GoJmespathExpressionGeneratorTest.java
Fixes #562
Basically, whenever you have a sub-expression (visit the left, then pass the result to the right), you need to check whether the left can be nil. If it can, then the generated code has to check for that, pre-declaring a variable for the result of the right, which the generated RHS code would then store the result in if it passes the nil check.
Take a look at the updated tests for some examples.
Verified that all downstream waiters in aws-sdk-go-v2 compile with this change (including the ones we haven't enabled generated path matchers for yet).
> fix potential nil deref in waiter path matcher

- transport/http/host.go
N/a
Fixes a small typo in the go doc of the `ValidHostLabel` function.
> transport/http: fix go doc typo

- .changelog/c898d340-9c15-4b9a-a5da-93a340a9d5f8.json
- transport/http/metrics.go
This PR fixes a race condition reported by #548,
by introducing a simple wrapper for time.Time.
While by default aws-sdk-go-v2 uses NopMeterProvider, the transport/http internals are still instrumenting the http requests (the withMetrics func).
Maybe there is a room for improvement, to not call httptrace.WithClientTrace when the meter is nop,
however this is out of scope for this PR.
> transport/http: fix metrics race condition

- .changelog/e16fb60e-d28a-11ef-828f-6a929c47a931.json
- io/ringbuffer_test.go
- middleware/logging_test.go
- private/protocol/middleware_capture_request_test.go
- testing/bytes.go
- testing/struct_test.go
- transport/http/middleware_close_response_body.go
- transport/http/middleware_http_logging_test.go
- transport/http/request.go
- transport/http/request_test.go
> refactor: fix deprecated for ioutil

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/GoJmespathExpressionGenerator.java
- codegen/smithy-go-codegen/src/test/java/software/amazon/smithy/go/codegen/GoJmespathExpressionGeneratorTest.java
There's an undocumented quirk in jmespath (as far as i could [find](https://jmespath.org/specification.html)) where `nil` numerics are coerced to 0 for order comparison.
e.g.
This fixes that in codegen. We caught this while attempting to turn on generated jmespath waiters for `autoscaling` in the Go SDK. This will be further verified when those changes are pulled in there.
> coerce nil numbers to 0 in jmespath codegen

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/protocol/DeserializeResponseMiddleware.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/protocol/SerializeRequestMiddleware.java
When doing some testing for CBOR, I realized we were not publishing metrics for serialization and deserialization. This PR fixes that.
Operation metrics are already being generated for CBOR methods as part of [OperationMetricsStruct](https://github.com/aws/smithy-go/blob/d2ad136d4774f0bef7fa710ddc774063ada2aa68/codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/OperationMetricsStruct.java#L70), so this just starts using them.
Note that there's no service that handles CBOR currently on the SDK, so this change won't have a corresponding change on the SDK
There are currently no methods on the SDK that directly use CBOR as their protocol, so testing was done as follows:
1. Modify a service that supports CBOR `JSON` description to generate CBOR methods
2. Run …
> Add metric and span support for CBOR serialize/deserialize

- transport/http/identity_test.go
#568 
Changes coming to Go 1.25 may break existing tests (see issue for more details) Updating how we do comparisons in the test
> Update identity test to not rely on comparing pointers to zero-sized objects

- Makefile
N/A
We've had some issues on our CI where the connection to Gradle gets killed. Adding a check to ensure the daemon is up. Will add this to our CI scripts
Ensured that this works by creating a `fail.sh` script that return 1 and ensuring that we wait the expected time and fail when invoking it
> why not only call `gradle status`?
Invoking just `gradle` can invoke a different version of Gradle than what we have on the wrapper
> Add a check for Gradle daemon status

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/protocol/DeserializeResponseMiddleware.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/protocol/SerializeRequestMiddleware.java
N/A
Similar to how we do on other [protocol generators](https://github.com/aws/smithy-go/blob/e6338ca9b5ee30c6317ea908173a369a9d3eb236/codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java#L363), we should manually close the serialization timers after we're done with serde. Otherwise, the timer will only be closed after the `defer` statement, which will happen after ALL the middleware has run.
`endTimer()` has a guard against being called multiple times and will only take the first value, so it's fine to add a manual call [ref](https://github.com/aws/smithy-go/blob/b17b84403740243c69345be7cd349d057ce6cbd3/codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/code …
> Close cbor serde timers to accurately measure middleware timing

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/protocol/DeserializeResponseMiddleware.java
N/A
Followup to #578
Deserialization timers were being called before we called `middleware.Next`, meaning that all middleware had to be invoked before we started the deserialization timers. This inflates the deserialization to take almost as long as the whole request.
This is already how this works on other protocols, see [existing code](https://github.com/aws/aws-sdk-go-v2/blob/6e064fa4372d87aabe78e74bc76ffda4445646d2/service/s3/deserializers.go#L50)
> Move CBOR deserialization timers to AFTER calling middleware.Next

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/protocol/rpc2/Rpc2SerializeRequestMiddleware.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/protocol/rpc2/cbor/SerializeMiddleware.java
N/A
With some new protocol tests in Smithy we realized we were not setting this header in cases where we needed to. Moving where we set this header to a more general place
> Move X-Amzn-Query-Mode header setup to always be included if the model has the awsQueryCompatible trait

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/protocol/rpc2/cbor/Rpc2CborProtocolGenerator.java
There's an ongoing discussion about the right way to match errors on CBOR. This would be one way of checking only against shape name instead of against shapeId. Don't merge this until the discussion is finalized
Diff would look like (`typ` is the full shape id)
```
-     switch string(typ) {
-     case "com.amazonaws.cloudwatch#ResourceNotFound": 
+     // namespace can be mangled by service, so matching by error shape name
+     errorParts := strings.Split(typ, "#")
+     errorName := errorParts[len(errorParts)-1]
+     switch string(errorName) {
+     case "ResourceNotFound": 
```
> Match CBOR errors via shape name instead of shapeId

- README.md
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/AbstractDirectedCodegen.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ShapeCodegenPlugin.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/ShapeDirectedCodegen.java
- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/server/ServerCodegenPlugin.java
- codegen/smithy-go-codegen/src/main/resources/META-INF/services/software.amazon.smithy.build.SmithyBuildPlugin
Base plugin for shape codegen, which is basically just client/server codegen without the service/operations. Doesn't affect the generated output of the downstream SDK at all.
Related to #571 but doesn't really close it.
> add go-shape-codegen plugin

- .changelog/ed10934bf38a4ea9a93df3498ffdfd8a.json
- document/json/encoder.go
- document/json/encoder_test.go
- document/json/shared_test.go
We've gotten correspondence about this a handful of times over the last quarter and it appears to be a behavioral requirement for some downstream AWS services in caching scenarios, so I'm just doing it. It also makes unit testing easier.
This DOES NOT cover general map serialization, that will have to be addressed downstream.
> sort map keys in JSON Document shape encodes

- codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/endpoints/EndpointResolverGenerator.java
Famously, Go fails to compile if a variable is declared but not used.
While testing, I noticed that when generating code for Smithy's [endpoint rule engine](https://smithy.io/2.0/additional-specs/rules-engine/index.html), if you declare a variable as `required` but don't actually use it, the generated code fails to compile.
This is because we always generate an intermediate variable for required parameters, and if unused, we fail to compile.
This change generates an intermediate throwaway to make the compiler happy, but breaking my heart.
> Allow unused required parameters in endpoint rule set

- aws-http-auth/internal/v4/signer.go
- aws-http-auth/internal/v4/signer_test.go
- aws-http-auth/sigv4/sigv4.go
- aws-http-auth/sigv4/sigv4_test.go
- aws-http-auth/sigv4a/sigv4a.go
- aws-http-auth/sigv4a/sigv4a_test.go
- aws-http-auth/v4/v4.go
This change adds support for SIGV4 and SIGV4A querystring signing. 
This is a feature of AWS Signature Version 4 request signing which places the computed request signature and related signing parameters directly into the request’s query string. This allows the service to authenticate requests based solely on URL parameters, without relying on HTTP headers for signature delivery.
* https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html
> Added support for SIG4/SIGV4A querystring authentication.
